### ISSUE TITLE
Reduces time and internet data consumption when git cloning

### ISSUE THREAD

**Issue by gaetan1903** [Jguer/yay#1934] opened 2023-02-23 04:28 UTC
### Is your feature request related to a problem? Please describe.

the git clone is too slow and consumes a lot of internet data when the repository is with a very large number of commits and branches

### Describe the solution you'd like

use --depth 1 when git clone the repository

### Describe alternatives you've considered

I think you don't need any history for the repository? well, why not clone just a single history to reduce and speed up cloning
### Additional context

if possible with git the cloning only the default branch, this very helpul too

**Comment by Jguer** [comment] 2023-02-23 13:58
Closing duplicate of https://github.com/Jguer/yay/issues/972

**Closed as completed by Jguer** 2023-02-23 13:58 UTC
Labels: Type: Feature Request, Status: Duplicate

**Comment by nikelborm** [comment] 2024-01-24 20:57
implemented here https://github.com/Jguer/yay/pull/2348
