### ISSUE TITLE
Dependency processing is broken!

### ISSUE THREAD

**Issue by zack24** [Jguer/yay#758] opened 2018-10-08 11:33 UTC
#### Affected Version
yay v8.1139 - libalpm v11.0.1
#### Steps to reproduce
0. clean new install 
1. yay -S ffmpeg-libfdk_aac
2. select the dependency like - libva
3. see the error message "Inner conflicts found"
It does appear each time at different step, because 3 dependency to confirm
yaourt doesn't have such an issue.
4. after "yaourt -S ffmpeg-libfdk_aac" succesfully completed - yay works too,
because no dependency to be solved.

My guess the problem is that single package libva which provides
libva.so, libva-x11.so and libva-drm.so at the same time.
Yay cannot handle such a case, where dependency is always the same package

Yaourt asks the same 3 questions and is able to provide each time the same option
among others in the list.

**Comment by Morganamilo** [comment] 2018-10-08 12:02
Please post the output.

**Comment by Morganamilo** [comment] 2018-10-08 12:37
>I guess I did it already: It prints "Inner conflicts found"
It does ask, whether I wish to use libva or libva1 or libva-git
I chose 1-default which is libva. It's enough for yay to fail.

>If I repeat the call sometimes, not always! it goes further and
ask whether I wish one of those 3 to satisfy next dependency.
It never though goes to the 3rd step.

No, the issue template specifically says to include the full output, not just one line. You're just describing the output, it would be much more helpful to just sent it verbatim.

>Those dependencies aren't packages, but files! See yourself:
check those which start with libva.

These are not files. They are just provides/depends. Makepkg has special handling for depends/provides ending in .so where it automatically appends the correct version of the libary.

**Comment by zack24** [comment] 2018-10-08 13:05
I can't make copy/pase anymore. The original output is gone. My scrolling is not unlimited.
But there is nothing more, then I say. You are free to generate the same output yourself on your system.

These ARE files and I have them now in my system. Well, speaking correctly they are soft links to the full library name with full version number. And yes those libraries are dependent to the given package.

My suggestion - don't teach others if you were not asked about. I came here to help and not to listen to your lessons. Here I stop. There is no point to continue this discussion. Not with you.

**Comment by zack24** [comment] 2018-10-08 13:12
For other noobs in the thread: http://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

**Comment by Morganamilo** [comment] 2018-10-08 13:17
>These ARE files and I have them now in my system. Well, speaking correctly they are soft links to the full library name with full version number. And yes those libraries are dependent to the given package.

>My suggestion - don't teach others if you were not asked about. I came here to help and not to listen to your lessons. Here I stop. There is no point to continue this discussion. Not with you.

Just wow. I will repeat, they are virtual dependencies. If a package has foo-1.so inside of it, then the pkgbuild maintainer will write `provides=(foo.so)` so that other packages can more easily depend on it. makepkg is smart and can automatically append the version number for you. 

Once the package is build they are no different to regular dependencies.

You can read it straight from the man page:
>If the dependency name appears to be a library (ends with .so), makepkg will try to find a binary that depends on the library in the built package and append the version needed by the binary. Appending the version yourself disables automatic detection.

**Comment by zack24** [comment] 2018-10-08 14:56
Didn't know you are a lady.
Please, be accurate when you argue topics which
1) have _nothing_ to do with reported problem (actually it's Necessary and Sufficient conditions)
2) my initial statement was - those are libraries represented in files comparing to packages representing in group of files! My intentions was only to show the difference between those. Making a hint for developers, cause it is the most probable the root of the problem!

Those _real_ dependencies might be treated equal to dependencies in a form of packages,
but the reality shows us it was not the case!

Please, try to be reasonable. It makes absolutely no sense to explain the broken behavior with the reference from the manual... The manual can only help if I was using the program in a wrong way.
But manual cannot help if program randomly fails at different stages.
Are we agree on this? - Hopefully, yes. Thanks and have a nice day.

**Comment by Morganamilo** [comment] 2018-10-08 15:58
>Didn't know you are a lady.
Please, be accurate when you argue topics which

What? Why do you feel a need to bring this up?

>have nothing to do with reported problem (actually it's Necessary and Sufficient condition)
my initial statement was - those are libraries represented in files comparing to packages representing in group of files! My intentions was only to show the difference between those. Making a hint for developers, cause it is the most probable the root of the problem!
Those real dependencies might be treated equal to dependencies in a form of packages,
but the reality shows us it was not the case!

All of this is literally unreadable.

>Please, try to be reasonable. It makes absolutely no sense to explain the broken behavior with the reference from the manual... The manual can only help if I was using the program in a wrong way.
But manual cannot help if program randomly fails at different stages.
Are we agree on this? - Hopefully, yes. Thanks and have a nice day.

I was explaining the behaviour because what you wrote was incorrect. Maybe you do know your stuff, but what you wrote, due to a language barrier or whatever else, was wrong.

I was not trying to use that behaviour to explain this away, I know this comes down to a limitation in yay (whatever that limitation is I don't know because you never provided the output, or at the very least the two packages in conflict). For now I'm just going to assume the root cause is the the same as #673 and close this.

Feel free to create a new issue, just please follow the template and **Include the full output**.

**Closed by Morganamilo** 2018-10-08 15:58 UTC

**Comment by zack24** [comment] 2018-10-08 16:29
I brought this up, because its impolite to blame a lady for what ever she has done. That is my mistake and I am sorry for this. Where you live it might be different, but that is not my concern.

I am not sure who are your teachers, but the grass they smoke is tough. If you just can blame my language it's a panic. It's not me who should be interested to solve the software bug.
And nope it's not a circular dependency how it's properly calls in #673. If neither you nor yay is able to recognize the simple circular dependency and solve it properly, than this piece of software is broken by design and can not be a replacement of well working yaourt.

I just repeat there is no circular dependency (new word for ya, he?) in my case. There is a single lib, yay has a problem with.

But I have a good news for you. Yay has been dropped from my systems. No more headache for you.

P.S. I always told myself filing the bugs is a very bad idea. People will blame you... How stupid I am...

**Comment by polygamma** [comment] 2018-10-08 18:15
> I brought this up, because its impolite to blame a lady for what ever she has done. That is my mistake and I am sorry for this. Where you live it might be different, but that is not my concern.

Are you even living in the 21st century?

**Comment by zack24** [comment] 2018-10-08 20:58
Offtopic Total: Nein. Gar nicht. Ich bin hier mit dem DeLorean angekommen und das was ich siehe gefällt mir gar nicht. Bei uns in 1985 die Leute waren in der Lage einander zu hören und zu verstehen. Wenn man jemandem hilft, der anderer sagt Danke und erzählt kein Quatsch. Auch die Frauen werden nicht angegriffen, was unter Männern als OK gilt. Aber heutzutage kann man beide von einander nicht unterscheiden. Es fehlt irgendwie an Toleranz obwohl man an jeder Ecke darüber spricht.
Ich habe die Frau wegen Inkompetenz angegriffen und bekenne mich schuldig. Und was höre ich?.. My only problem I've lost my DeLorean. Sorry for being here. Will try to avoid this place. Sorry again.

**Comment by Morganamilo** [comment] 2018-10-08 21:05
Enough is enough. Locking...

**Comment by Morganamilo** [comment] 2018-10-08 21:22
For some actual useful information:

```
yay -Sybdb ffmpeg-libfdk_aac
[sudo] password for morganamilo: 
:: Synchronising package databases...
 multilib is up to date
 testing is up to date
 community-testing                             10.2 KiB  0.00B/s 00:00 [---------------------------------------] 100%
 multilib-testing is up to date
 core is up to date
 extra is up to date
 community                                      4.6 MiB  3.91M/s 00:01 [---------------------------------------] 100%
:: There are 6 providers available for ffmpeg-libfdk_aac:
:: Repository AUR
    1) ffmpeg-libfdk_aac 2) ffmpeg-full 3) ffmpeg-full-arm-git 4) ffmpeg-full-git 5) ffmpeg-qsv 6) ffmpeg-semifull-git 

Enter a number (default=1): 
:: There are 3 providers available for libva-x11.so:
:: Repository multilib
    1) lib32-libva1 
:: Repository extra
    2) libva 
:: Repository community
    3) libva1 

Enter a number (default=1): 
:: There are 2 providers available for lib32-libgl:
:: Repository multilib
    1) lib32-libglvnd 2) lib32-nvidia-340xx-utils 

Enter a number (default=1): 
:: There are 4 providers available for libvpx.so:
:: Repository multilib
    1) lib32-libvpx 2) lib32-libvpx1.3 
:: Repository extra
    3) libvpx 
:: Repository community
    4) libvpx1.3 

Enter a number (default=1): 
:: Checking for conflicts...
:: Checking for inner conflicts...

==> Inner conflicts found:
 -> ffmpeg-libfdk_aac: ffmpeg
Unresolvable package conflicts, aborting
```

```
 -> ffmpeg-libfdk_aac: ffmpeg
```
The dependency tree pulls in ffmpeg and ffmpeg-libfdk_aac. It would appear ffmpeg is needed in order to build ffmpeg-libfdk_aac. Of course both can't be installed at the same time so yay errors with an inner conflict.

I'm tempted to just make inner conflicts non fatal and let yay swap out ffmpeg with ffmpeg-libfdk_aac as it goes. Of course this is not full proof as there could be an inner conflict where package b does not provide package a. So in that case yay would try to swap them and get a dependency error.

We already do this for normal conflicts really. If ffmpeg was already installed then yay will warn that it will be swapped out but it does not check if the swap will fail.

This doesn't seem like much of a problem as 99% of conflicts are usually between different editions of the same package e.g. -git vs release.

Anyway, this is essentially the same problem as #673, has nothing to do with .so files, nor a package providing multiple things.

For those with an actual intrest that have something relevant to say, #673 is still open.
