### ISSUE TITLE
"yay -Ss git" fails to return any packages.

### ISSUE THREAD

**Issue by dicedblob** [Jguer/yay#1756] opened 2022-06-02 17:33 UTC
### Affected Version

yay v11.1.2 - libalpm v13.0.1

### Describe the bug

$ yay -Ss git

results in no packages returned at all.

### Reproduction Steps

1. Run "yay -Ss git"

### Expected behavior

Output a list of git related packages, at least from the arch repos.

### Output

 -> Error during AUR search: status 200: Too many package results.

 -> Showing repo packages only
 -> no query was executed

```sh

```

**Comment by Jguer** [comment] 2022-06-17 08:36
Unable to reproduce, the aur failing to query for "git" is normal and expected behavior. 
The repositories not returning any result could indicate there was no cache (running `yay -Sy or pacman -Sy` should handle that).

Closing as can't reproduce

**Closed as completed by Jguer** 2022-06-17 08:36 UTC
Labels: Type: Bug, Status: Cannot Reproduce
