### ISSUE TITLE
removemake option / dependencies not been removed after installation

### ISSUE THREAD

**Issue by cysp74** [Jguer/yay#1481] opened 2021-03-27 09:17 UTC
### Affected Version
yay v10.2.0.r8.g2da1e15 - libalpm v12.0.2

### Describe the bug
Yay doesn't remove make dependencies after installation.
Doesn't offer interactive selectable option.
Checked with "removemake" option also.

yay -sc recognizes installed dependencies can able to remove.

### Reproduction Steps
yay -S <wanted package>

### Expected behavior

Remove dependencies

### Output
config:

{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "---",
	"absdir": "---",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "yes",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": true,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}

**Comment by grandchild** [comment] 2021-03-31 13:14
* Which package were you installing?
* Are you sure that none of the make-dependencies are optional dependencies for other packages you have installed? Have a look with `yay -Qi $PACKAGE | grep Optional`.
* Were no make-dependencies removed, or were some of them removed and others not?

**Comment by cysp74** [comment] 2021-03-31 13:26
1. You mean Eg. wine-staging-git, geany-git, srain-git.
2. Quite certain, before updating packages above yay installed prereqs
for make, but after no installed packages removed.
3. no make deps removed at all.

+1 yay -sc removes make deps without hassle after yay -S <packages
above>

Thanks.

-----Original Message-----
From: jakob ***@***.***>
Reply-To: Jguer/yay
***@***.***>
To: Jguer/yay ***@***.***>
Cc: cysp74 ***@***.***>, Author ***@***.***>
Subject: Re: [Jguer/yay] removemake option / dependencies not been
removed after installation (#1481)
Date: Wed, 31 Mar 2021 06:15:04 -0700

 * Which package were you installing?
 * Are you sure that none of the make-dependencies are optional
   dependencies for other packages you have installed? Have a look with
   yay -Qi $PACKAGE | grep Optional.
 * Were no make-dependencies removed, or were some of them removed and
   others not?

**Comment by grandchild** [comment] 2021-03-31 16:47
I just tried with `geany-git`. Both with `"removemake"` set to `"ask"` and answering yes at the prompt, as well as when setting it to `"yes"`: Both times installing it did successfully install _and uninstall_ `doxygen` and `python-reportlab` (the two make-dependencies I happened to miss).

**Comment by cysp74** [comment] 2021-03-31 19:22
[yyy@xxxx ~]$ yay -S geany-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo:5]  doxygen-1.9.1-1  python-docutils-0.16-4  libimagequant-2.14.1-1  python-pillow-8.1.2-1  python-reportlab-3.5.66-1
[Aur:1]  geany-git-1.36.0.r49.gd8f532b5a-1

  1 geany-git                        (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): geany-git
  1 geany-git                        (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: geany-git
[sudo] password for home: 
resolving dependencies...
looking for conflicting packages...

Packages (5) doxygen-1.9.1-1  libimagequant-2.14.1-1  python-docutils-0.16-4  python-pillow-8.1.2-1  python-reportlab-3.5.66-1

Total Installed Size:  32,31 MiB

:: Proceed with installation? [Y/n] 
(5/5) checking keys in keyring                                                                                            [##########################################################################] 100%
(5/5) checking package integrity                                                                                          [##########################################################################] 100%
(5/5) loading package files                                                                                               [##########################################################################] 100%
(5/5) checking for file conflicts                                                                                         [##########################################################################] 100%
(5/5) checking available disk space                                                                                       [##########################################################################] 100%
:: Processing package changes...
(1/5) installing doxygen                                                                                                  [##########################################################################] 100%
Optional dependencies for doxygen
    graphviz: for caller/callee graph generation [installed]
    qt5-base: for doxywizard [installed]
(2/5) installing python-docutils                                                                                          [##########################################################################] 100%
(3/5) installing libimagequant                                                                                            [##########################################################################] 100%
(4/5) installing python-pillow                                                                                            [##########################################################################] 100%
Optional dependencies for python-pillow
    freetype2: for the ImageFont module [installed]
    libraqm: for complex text scripts [installed]
    libwebp: for webp images [installed]
    tk: for the ImageTK module
    python-olefile: OLE2 file support
    python-pyqt5: for the ImageQt module
(5/5) installing python-reportlab                                                                                         [##########################################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Keep the last cache and the currently installed.
==> no candidate packages found for pruning
==> Making package: geany-git 1.36.0.r49.gd8f532b5a-1 (2021. xxx. 31., xxx, 21:14:54 )
==> Retrieving sources...
  -> Updating geany git repo...
Fetching origin
==> Validating source files with md5sums...
    geany ... Skipped
 -> doxygen not satisfied, flushing install queue
==> Making package: geany-git 1.36.0.r49.gd8f532b5a-1 (2021. xxx. 31., xxx, 21:14:56 )
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating geany git repo...
Fetching origin
==> Validating source files with md5sums...
    geany ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of geany git repo...
Cloning into 'geany'...
done.
==> Starting prepare()...
==> Starting pkgver()...
==> Updated version: geany-git 1.37.1.r37.g41624c411-1
==> Sources are ready.
==> Making package: geany-git 1.37.1.r37.g41624c411-1 (2021. xxx. 31., xxx, 21:14:59 )
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
 -> geany-git-1.37.1.r37.g41624c411-1 already made -- skipping build
 -> Found git repo: github.com/geany/geany.git
loading packages...
warning: geany-git-1.37.1.r37.g41624c411-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) geany-git-1.37.1.r37.g41624c411-1

Total Installed Size:  11,70 MiB
Net Upgrade Size:       0,00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                            [##########################################################################] 100%
(1/1) checking package integrity                                                                                          [##########################################################################] 100%
(1/1) loading package files                                                                                               [##########################################################################] 100%
(1/1) checking for file conflicts                                                                                         [##########################################################################] 100%
(1/1) checking available disk space                                                                                       [##########################################################################] 100%
:: Processing package changes...
(1/1) reinstalling geany-git                                                                                              [##########################################################################] 100%
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Updating icon theme caches...
(3/4) Keep the last cache and the currently installed.
==> no candidate packages found for pruning
(4/4) Updating the desktop file MIME type cache...
removing untracked AUR files from cache...
:: Cleaning (1/1): /home/home/.cache/yay/geany-git
[yyy@xxxx ~]$ yay -sc
checking dependencies...

Packages (5) doxygen-1.9.1-1  libimagequant-2.14.1-1  python-docutils-0.16-4  python-pillow-8.1.2-1  python-reportlab-3.5.66-1

Total Removed Size:  32,31 MiB

:: Do you want to remove these packages? [Y/n] 
:: Processing package changes...
(1/5) removing python-reportlab                                                                                           [##########################################################################] 100%
(2/5) removing python-pillow                                                                                              [##########################################################################] 100%
(3/5) removing python-docutils                                                                                            [##########################################################################] 100%
(4/5) removing libimagequant                                                                                              [##########################################################################] 100%
(5/5) removing doxygen                                                                                                    [##########################################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Keep the last cache and the currently installed.
==> no candidate packages found for pruning
[yyy@xxxx ~]$ grep make  ~/.config/yay/config.json 
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"removemake": "yes",
[yyy@xxxx ~]$

**Comment by grandchild** [comment] 2021-03-31 21:15
Ah, I'm so sorry. I _can_ reproduce with yay-git. So one of the last 8 commits did break this.

**Comment by Jguer** [comment] 2021-04-05 15:31
Time to start digging I guess

**Comment by goodgerster** [comment] 2021-05-02 20:48
I'm experiencing the same problem with `yay-bin` version 10.2.1-1 when building `inkscape-git`.

**Comment by walwan** [comment] 2021-05-03 10:28
> [yyy@xxxx ~]$ yay -S geany-git
> :: Checking for conflicts...
> :: Checking for inner conflicts...
> [Repo:5] doxygen-1.9.1-1 python-docutils-0.16-4 libimagequant-2.14.1-1 python-pillow-8.1.2-1 python-reportlab-3.5.66-1
> [Aur:1] geany-git-1.36.0.r49.gd8f532b5a-1


It seems that yay cannot tell makedeps from other deps since I would expect packages like "doxygen" to be in "repo make" list instead of "repo" list.

**Comment by goodgerster** [comment] 2021-05-05 10:16
I think I can confirm @walwan's hypothesis:

```
ben@hermes ~> yay -S inkscape-git
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo:3]  boost-1.75.0-3  intltool-0.51.0-6  gmock-1.10.0-3
[Aur:1]  inkscape-git-5:1.1.alpha.r199.g30c0b84b2b-1

✀

ben@hermes ~> yay -c
checking dependencies...

Package (3)  Old Version  Net Change 

boost        1.75.0-3     -167.58 MiB
gmock        1.10.0-3       -0.98 MiB
intltool     0.51.0-6       -0.15 MiB
```

**Comment by Jguer** [comment] 2021-05-05 20:42
Yes I confirm this a regression in this version of yay, the install is properly done but the separation on the categories got bugged

**Comment by workonfire** [comment] 2021-05-06 11:05
Can confirm as well, this happens on `yay v10.2.1.r9.g767c797 - libalpm v12.0.2`. Yay sometimes mixes regular dependencies with makedepends, even though there aren't any, or they're already installed.
```
krystian:~/ $ yay -S babi
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo Make:1]  python-identify-2.2.4-1
[Aur:1]  babi-0.0.21-1
[Aur Make:2]  python-onigurumacffi-1.1.0-1  babi-grammars-0.0.24-1
```
Expected output based on the [babi](https://aur.archlinux.org/packages/babi/) package:
```
[Repo:1]  python-identify-2.2.4-1
[Aur:3]  babi-0.0.21-1 python-onigurumacffi-1.1.0-1 babi-grammars-0.0.24-1
```

When pacman installs the package, it indicates that there's something wrong:
```
:: Processing package changes...
(1/1) installing babi                                    [------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
checking dependencies...
warning: removing python-onigurumacffi from target list
warning: removing babi-grammars from target list
warning: removing python-identify from target list
 there is nothing to do
krystian:~/ $  
```
and `yay -c` then does nothing (as expected).

**Comment by Jguer** [comment] 2021-05-07 22:45
@workonfire  @goodgerster @cysp74 can you confirm this issue is fixed in `yay-git`?

**Comment by workonfire** [comment] 2021-05-08 08:10
Yes. It's working as expected.

**Comment by goodgerster** [comment] 2021-05-12 22:02
Appears to be fine on `yay v10.2.2 - libalpm v12.0.2`:

```
ben@hermes ~> yay -S inkscape-git
:: Checking for conflicts...
:: Checking for inner conflicts...
 -> 
Package conflicts found:
 -> Installing inkscape-git will remove: inkscape
[Repo Make:7]  opencl-headers-2:2021.04.29-1  chrpath-0.16-3  ghostpcl-9.54.0-2  ghostxps-9.54.0-2  jbigkit-2.1-5  boost-1.75.0-3  intltool-0.51.0-6
[Aur:2]  imagemagick6-6.9.12.12-1 (libmagick6)  inkscape-git-5:1.1.alpha.r199.g30c0b84b2b-1

  2 imagemagick6 (libmagick6)        (Build Files Exist)
  1 inkscape-git                     (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
```

Thanks.

**Comment by Jguer** [comment] 2021-05-13 17:41
Yeah, this was my bad implementing `-dd`, I'm working towards reducing the frequency of these. Thanks for the patience

**Closed as completed by Jguer** 2021-05-13 17:41 UTC
Labels: Type: Bug, Status: Resolved
