### ISSUE TITLE
yay -c issue

### ISSUE THREAD

**Issue by falsera1n** [Jguer/yay#2091] opened 2023-04-06 20:50 UTC
yay -v = yay v12.0.3 - libalpm v13.0.2
issue: when trying to yay -c, it says error: invalid option: '--clean' and '--refresh' may not be used together
 -> exit status 1
appeared after update. 
didnt do anything to yay at all, and this is fresh install.
arch linux, installed yay from https://aur.archlinux.org/packages/yay git url with makepkg.
screenshots:
![image](https://user-images.githubusercontent.com/126025701/230491314-c4c1c6b7-93eb-4aee-aeac-9428c147acf0.png)

**Comment by Jguer** [comment] 2023-04-06 20:56
closing as intended change https://github.com/Jguer/yay/releases/tag/v12.0.0

duplicate of https://github.com/Jguer/yay/issues/2049

**Closed as completed by Jguer** 2023-04-06 20:56 UTC
Labels: Type: Bug, Status: Triage
