### ISSUE TITLE
Packages being wrongfully excluded

### ISSUE THREAD

**Issue by AFWL** [Jguer/yay#2515] opened 2024-09-29 10:08 UTC
### Affected Version

```
yay v12.4.2 - libalpm v15.0.0
```

### Describe the bug

When presented with a list of packages to exclude, excluding all packages between the first and last package will cause the last package to be wrongfully excluded.

### Reproduction Steps

1. Run yay
2. Select packages to exclude (everything between the first and last package)

### Expected behavior

Given the following list of packages (see output), yay should only exclude lib32-glibc-eac, lact, glibc-eac-locales and glibc-eac.

### Output

```
:: Synchronising package databases...
 core is up to date
 extra is up to date
 multilib is up to date
:: Searching AUR for updates...
:: Checking development packages...
:: There are 2 providers available for cargo:
:: Repository extra
    1) rust 2) rustup 

Enter a number (default=1): 
==> 
:: Searching databases for updates...
 -> hyprland: ignoring package upgrade (0.42.0-2 => 0.43.0-1)
 -> Packages not in AUR: nwg-look-bin  shell-color-scripts
 -> Flagged Out Of Date AUR Packages: proton-ge-custom-bin
:: 3 dependencies will also be installed for this operation.
   extra/gd     -> 2.3.3-8
   (make dependency of glibc-eac, glibc-eac-locales, ...)
   extra/gdb    -> 15.1-1
   (make dependency of hyprcursor-git)
   extra/rust   -> 1:1.81.0-1
   (make dependency of lact)

:: 6 packages to upgrade/install.
6  aur/coolercontrold-bin  1.4.1-2               -> 1.4.2-2
5  aur/glibc-eac           2.39-4                -> 2.40-1
4  aur/glibc-eac-locales   2.39-4                -> 2.40-1
3  aur/lact                0.5.4-0               -> 0.5.6-1
2  aur/lib32-glibc-eac     2.39-4                -> 2.40-1
1  devel/hyprcursor-git    0.1.9.r11.g912d5602-1 -> latest-commit
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
 -> Excluding packages may cause partial upgrades and break systems
==> 2-5
AUR Explicit (1): hyprcursor-git-latest-commit
Sync Make Dependency (1): gdb-15.1-1
:: PKGBUILD up to date, skipping download: hyprcursor-git
  1 hyprcursor-git                   (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
```

**Comment by jdholtz** [comment] 2024-10-05 16:37
This appears to be a duplicate of #2381.

**Closed as completed** 2024-10-08 10:53 UTC
Labels: Type: Bug, Status: Triage
