### ISSUE TITLE
Wrong formatting of download progress

### ISSUE THREAD

**Issue by thatsthat** [Jguer/yay#2279] opened 2023-09-15 07:45 UTC
### Affected Version
yay v12.1.2 - libalpm v13.0.2
6.5.3-arch1-1
alacritty 0.12.2 (9d9982df)
oh-my-zsh + powerlevel10k theme

### Describe the bug

Download progress on some community packages produces multiple lines with wrong formatting

### Reproduction Steps

1. Run 'yay' command
2. Wait for AUR packages to download
3. Observe the multiple lines of scrambled text instead of a single line with download progress

### Expected behavior

A single line with download progress would be expected (as with official packages)

### Output

  ```
-> Found visual-studio-code-bin.sh
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  -> Downloading code_x64_1.82.2.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134  100   134    0     0    421      0 --:--:-- --:--:-- --:--:--   422
34 7 41.44 M  1 2 93M4   2 51.48 M1 9 . 1 M  0   0         00    349582k6  2 k     0     0 :000: 3 3 0 :00:000::014 7  0 :000::2090 43:700k6
21  129M   21 27.5M    0     0  4052k      0  0:00:32  0:00:06  0:00:26 4310 8k37.4M    0     0  4662k      0  0:00:16  0:00:08  0:00:08 5972
8358  6 41.209MM       308    4 9 0.  64M9 6 3 k  0      0  0:00 : 1 5  0  0 :40205:41k3     0 : 00 :00 2  05:00:31  04:5080k:11  0:00:20 45
100 74.4M  100 74.4M    0     0  5051k      0  0:00:15  0:00:15 --:--:-- 6160k

```

**Comment by Jguer** [comment] 2023-09-16 08:42
Duplicate of https://github.com/Jguer/yay/issues/1620

**Closed as completed by Jguer** 2023-09-16 08:42 UTC
Labels: Type: Bug, Status: Duplicate
