### ISSUE TITLE
add `pacman -S fakeroot binutils` to installation

### ISSUE THREAD

**Issue by Quoteme** [Jguer/yay#1196] opened 2020-02-24 02:47 UTC
#### Issue
When installing yay on a fresh arch install it throws errors about missing packages. This can be fixed by installing fakeroot and binutils

#### Steps to reproduce
1. install the latest arch linux
2. follow the steps provided in the installation section of _yay_

#### Output
```
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
==> ERROR: Cannot find the fakeroot binary.
==> ERROR: Cannot find the strip binary required for object file stripping.
```

**Comment by sylvainbx** [comment] 2020-02-24 20:43
I agree, this should be at least documented. Also: `make` and `gcc` are some requirements for the makepkg command to succeed.

**Comment by Jguer** [comment] 2020-02-25 22:09
Duplicate of

#1007 
#1130

**Closed by Jguer** 2020-02-25 22:09 UTC
