### ISSUE TITLE
Fails to update AUR packages (after package "already made")

### ISSUE THREAD

**Issue by lavara123** [Jguer/yay#1848] opened 2022-12-08 05:39 UTC
Trying to update updated package while updating aur packages. Finally it says this package is already up to date but still in the update list

**Comment by grandchild** [comment] 2022-12-08 15:22
Which package? Please follow the issue template, or at the very least copy your terminal output here. Thanks

**Comment by lavara123** [comment] 2022-12-08 15:28
> Which package? Please follow the issue template, or at the very least copy your terminal output here. Thanks

![Ekran görüntüsü_2022-12-08_18-25-03](https://user-images.githubusercontent.com/12005386/206486169-f1cd9c02-af76-42cb-94ca-cbed4e1b347c.png)

already updated the ones in the photo but still in the list




and it says:

already made -- skipping build

**Comment by grandchild** [comment] 2022-12-08 15:35
can you show the output of `yay -Q flutter` or `yay -Q visual-studio-code-bin`?

**Comment by lavara123** [comment] 2022-12-08 15:36
@grandchild sorry just says that and skips the update
already made -- skipping build

my vs code version => 1.73.1
aur vs code version => 1.74.0

so it doesn't actually update

**Comment by lavara123** [comment] 2022-12-08 15:38
> yay -Q visual-studio-code-bin

visual-studio-code-bin 1.73.1-2


I'd skip the flutter package. Because flutter updates itself, spring gives an error

**Comment by grandchild** [comment] 2022-12-08 23:34
okay, so what happens when you _do_ try to upgrade?
can you show the _complete_ output of `yay -S visual-studio-code-bin`?
(and please just copy and paste from your terminal, don’t make a screenshot, they’re harder to read — use a \`\`\` (triple-backtick) section, thanks)

**Comment by lavara123** [comment] 2022-12-09 05:48
```bash
yay -S visual-studio-code-bin
:: Çakışmalar kontrol ediliyor...
:: İç çakışmalar kontrol ediliyor...
[Aur:1]  visual-studio-code-bin-1.74.0-1

  1 visual-studio-code-bin                  (Kuruldu)(Kurulum Dosyaları Var)
==> cleanBuild yapılacak paketler?
==> [N]Hiçbiri [A]Hepsi [Ab]İptal [I]Kurulmuş [No]Kurulmamış veya (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD güncel, Atlanıyor (1/0): visual-studio-code-bin
  1 visual-studio-code-bin                  (Kuruldu)(Kurulum Dosyaları Var)
==> Gösterilecek olan değişiklikler (diff)?
==> [N]Hiçbiri [A]Hepsi [Ab]İptal [I]Kurulmuş [No]Kurulmamış veya (1 2 3, 1-3, ^4)
==> 
:: (1/1) SRCINFO çözümleniyor: visual-studio-code-bin
==> visual-studio-code-bin 1.74.0-1 (Cum 09 Ara 2022 08:46:21) paketi oluşturuluyor
==> Kaynaklar getiriliyor...
  -> code.desktop bulundu
  -> code-url-handler.desktop bulundu
  -> visual-studio-code-workspace.xml bulundu
  -> visual-studio-code-bin.sh bulundu
  -> code_x64_1.74.0.tar.gz bulundu
==> source ile sha256sums dosyası doğrulanıyor...
    code.desktop ... Doğrulandı
    code-url-handler.desktop ... Doğrulandı
    visual-studio-code-workspace.xml ... Doğrulandı
    visual-studio-code-bin.sh ... Doğrulandı
==> source_x86_64 ile sha256sums dosyası doğrulanıyor...
    code_x64_1.74.0.tar.gz ... Doğrulandı
==> visual-studio-code-bin 1.74.0-1 (Cum 09 Ara 2022 08:46:24) paketi oluşturuluyor
==> Bağımlılıklar denetleniyor...
==> Derleme bağımlılıkları denetleniyor...
==> Kaynaklar getiriliyor...
  -> code.desktop bulundu
  -> code-url-handler.desktop bulundu
  -> visual-studio-code-workspace.xml bulundu
  -> visual-studio-code-bin.sh bulundu
  -> code_x64_1.74.0.tar.gz bulundu
==> source ile sha256sums dosyası doğrulanıyor...
    code.desktop ... Doğrulandı
    code-url-handler.desktop ... Doğrulandı
    visual-studio-code-workspace.xml ... Doğrulandı
    visual-studio-code-bin.sh ... Doğrulandı
==> source_x86_64 ile sha256sums dosyası doğrulanıyor...
    code_x64_1.74.0.tar.gz ... Doğrulandı
==> Mevcut $srcdir/ dizini kaldırılıyor ...
==> Kaynaklar açılıyor...
  -> code_x64_1.74.0.tar.gz ile bsdtar açılıyor
==> Kaynak kodları hazır.
==> visual-studio-code-bin 1.74.0-1 (Cum 09 Ara 2022 08:46:31) paketi oluşturuluyor
==> Bağımlılıklar denetleniyor...
==> Derleme bağımlılıkları denetleniyor...
==> UYARI: Mevcut $srcdir/ ağacı kullanılıyor
==> Kaynak kodları hazır.
 -> visual-studio-code-bin-1.74.0-1 çoktan yapıldı -- yapılandırma atlanıyor
[sudo] password for lavara123: 
[lavara123@ArchLinux]─[~]
```

**Comment by grandchild** [comment] 2022-12-09 17:21
> -> visual-studio-code-bin-1.74.0-1 already done -- skipping
[sudo] password for lavara123: 

After this, it should install the package but somehow it doesn't start the installation. Does it immediately quit? Or does it wait a bit before showing your prompt again?

**Comment by grandchild** [comment] 2022-12-09 17:22
Or did you abort with Ctrl-C at that point?

**Comment by lavara123** [comment] 2022-12-09 17:23
> 

leaves immediately :/

**Comment by lavara123** [comment] 2022-12-09 17:24
> Or did you abort with Ctrl-C at that point?

No, leaves immediately

**Comment by verygenericname** [comment] 2022-12-09 23:11
same here, doesn't even update my packages

**Comment by verygenericname** [comment] 2022-12-09 23:11
![image](https://user-images.githubusercontent.com/87825638/206810134-d4c0fbf5-3cc3-4ab8-bb4c-8bfdb3e639bb.png)

**Comment by verygenericname** [comment] 2022-12-09 23:11
![image](https://user-images.githubusercontent.com/87825638/206810150-83ba129f-6889-40a3-8d1a-da1dd235bfb6.png)

**Comment by Focron** [comment] 2022-12-10 00:55
I also have the same Issue, it Just wont update

**Comment by pieterjandejaegere** [comment] 2022-12-10 09:10
I have this problem as well, packages are not updated with the message `*package* already made -- skipping build`

**Comment by lavara123** [comment] 2022-12-10 15:38
@grandchild  I solved the problem by completely uninstalling yay and reinstalling it.

**Comment by chandujr** [comment] 2022-12-10 18:41
I am also facing this same issue.

**Comment by grandchild** [comment] 2022-12-11 15:12
> I have this problem as well, packages are not updated with the message `*package* already made -- skipping build`

@pieterjandejaegere this is normal. it just means that the package doesn’t need to be created from source anymore. it’s not actually an error message.

**Comment by jamessouth** [comment] 2022-12-14 23:58
I found this issue because of a similar problem with `yay-git` (flagged out of date 2022-11-24) that had the same result of not installing the updated package. I fixed by replacing `yay-git` with `yay` with this line from the README: `pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si`

**Comment by Jguer** [comment] 2022-12-15 07:15
Will investigate, might be some unintended change to the legacy engine (pkg archive path not getting added because it's already made).

`yay -V` would help in this case.

If you're on `yay-git` enable `debug` in your `~/.config/yay/config.json` (`"debug": true`) and post the output of the command if it's still reproducible

**Comment by adrinjalali** [comment] 2022-12-15 10:27
I think I have the same issue, enabling `debug`, this is what I get:

```bash
$ yay -S visual-studio-code-bin
[DEBUG] populating db executor package caches. sync_len 1388 remote_len 18
[DEBUG] AUR RPC: [visual-studio-code-bin]
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  visual-studio-code-bin-1.74.1-1

  1 visual-studio-code-bin                   (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/0): visual-studio-code-bin
  1 visual-studio-code-bin                   (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
[DEBUG] capturing /usr/bin/git -C /home/adrin/.cache/yay/visual-studio-code-bin reset --hard HEAD
[DEBUG] capturing /usr/bin/git -C /home/adrin/.cache/yay/visual-studio-code-bin merge --no-edit --ff
:: (1/1) Parsing SRCINFO: visual-studio-code-bin
[DEBUG] running /usr/bin/makepkg --verifysource -Ccf --ignorearch

==> Making package: visual-studio-code-bin 1.74.1-1 (Thu 15 Dec 2022 11:26:38 AM CET)
==> Retrieving sources...
  -> Found code.desktop
  -> Found code-url-handler.desktop
  -> Found visual-studio-code-workspace.xml
  -> Found visual-studio-code-bin.sh
  -> Found code_x64_1.74.1.tar.gz
==> Validating source files with sha256sums...
    code.desktop ... Passed
    code-url-handler.desktop ... Passed
    visual-studio-code-workspace.xml ... Passed
    visual-studio-code-bin.sh ... Passed
==> Validating source_x86_64 files with sha256sums...
    code_x64_1.74.1.tar.gz ... Passed
[DEBUG] running /usr/bin/makepkg --nobuild -fC --ignorearch
==> Making package: visual-studio-code-bin 1.74.1-1 (Thu 15 Dec 2022 11:26:44 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found code.desktop
  -> Found code-url-handler.desktop
  -> Found visual-studio-code-workspace.xml
  -> Found visual-studio-code-bin.sh
  -> Found code_x64_1.74.1.tar.gz
==> Validating source files with sha256sums...
    code.desktop ... Passed
    code-url-handler.desktop ... Passed
    visual-studio-code-workspace.xml ... Passed
    visual-studio-code-bin.sh ... Passed
==> Validating source_x86_64 files with sha256sums...
    code_x64_1.74.1.tar.gz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting code_x64_1.74.1.tar.gz with bsdtar
==> Sources are ready.
[DEBUG] capturing /usr/bin/makepkg --packagelist
[DEBUG] running /usr/bin/makepkg -c --nobuild --noextract --ignorearch
==> Making package: visual-studio-code-bin 1.74.1-1 (Thu 15 Dec 2022 11:26:56 AM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
 -> visual-studio-code-bin-1.74.1-1 already made -- skipping build
[DEBUG] running /usr/bin/su -c pacman -D -q --asexplicit --noconfirm --config /etc/pacman.conf -- visual-studio-code-bin
Password: 
```

Nothing happens after I enter my password.

__UPDATE__: manually replacing `yay-git` with a version from git clone as suggested in https://github.com/Jguer/yay/issues/1848#issuecomment-1352375527 fixed my issue.

**Comment by Jguer** [comment] 2022-12-15 19:22
I thought I was able to reproduce it but I can't in the latest `yay-git`.

@adrinjalali Can you see if installing the latest version of `yay-git` fixed the issue and if not can you share the contents of your `~/.config/yay/config.json`? 

---

From your debug logs the following seems to be missing

```
[DEBUG] deps: [] exp: [visual-studio-code-bin] pkgArchives: [~/.cache/yay/visual-studio-code-bin/visual-studio-code-bin-1.74.1-1-x86_64.pkg.tar.zst]
[DEBUG] checking vcs store for: visual-studio-code-bin
[DEBUG] installing archives: [~/.cache/yay/visual-studio-code-bin/visual-studio-code-bin-1.74.1-1-x86_64.pkg.tar.zst]
[DEBUG] running /usr/bin/sudo pacman -U --config /etc/pacman.conf -- ~/.cache/yay/visual-studio-code-bin/visual-studio-code-bin-1.74.1-1-x86_64.pkg.tar.zst
```

As well as the mention of an empty batch install which would mean `batchinstall` was enabled in the config

EDIT: changing the privilege elevator to `su` also worked

**Comment by RyanDenton** [comment] 2022-12-16 01:42
@grandchild I have also solved this problem by uninstalling yay-git and reinstalling yay

**Comment by adrinjalali** [comment] 2022-12-16 10:37
My config file is pretty empty.

```
{
	"debug": true
}
```

> Can you see if installing the latest version of yay-git fixed the issue

It was up to date when the issue was triggered. 

> From your debug logs the following seems to be missing

I agree. It was as if after entering password it gracefully quits for some reason.

**Comment by Euro-pol** [comment] 2022-12-16 17:19
> I found this issue because of a similar problem with `yay-git` (flagged out of date 2022-11-24) that had the same result of not installing the updated package. I fixed by replacing `yay-git` with `yay` with this line from the README: `pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si`

this worked ^^^

**Comment by m1guelperez** [comment] 2022-12-25 22:05
Jup, have the same issue.

**Comment by Jguer** [comment] 2022-12-26 23:21
@m1guelperez can you share stdout output for the issue, yay config and privilege elevator used (su/sudo/doas?)

**Comment by Jguer** [comment] 2022-12-26 23:28
> > I found this issue because of a similar problem with `yay-git` (flagged out of date 2022-11-24) that had the same result of not installing the updated package. I fixed by replacing `yay-git` with `yay` with this line from the README: `pacman -S --needed git base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si`
> 
> this worked ^^^

This might solve your issue temporarily but in January I'll promote the version in `yay-git` to `yay` and the issue will return. Before switching to the `yay` it really helps to share the answer to these questions in this issue:

- Output of `yay -Pg`
- Output of `yay -V`
- Command used
- Was yay running as root at the time of the issue?  
- What is your privilege elevator (su/sudo/doas?)
- What package you were trying to install and was the package already installed (previous version or same version)

Thanks :smile:

**Comment by m1guelperez** [comment] 2022-12-28 19:19
> @m1guelperez can you share stdout output for the issue, yay config and privilege elevator used (su/sudo/doas?)

I actually immediately used the work-around proposed above. Therefore, I think you don't need my output anymore?

**Comment by adrinjalali** [comment] 2023-01-02 10:53
I have this on questions you have @Jguer :

- command used: `yay --sudo=su -Syu`, but `yay --sudo=su -S visual-studio-code-bin` would do the same
- no it wasn't running as root, it was in a normal non-sudoer user with `--sudo=su`
- privilege elevator: `su`
- It was upgrading an already installed package: `visual-studio-code-bin`

The `--sudo=su` is not visible in the my original log since I have `yay --sudo=su` as an alias which I had forgotten about.

**Comment by dcaiafa** [comment] 2023-01-09 18:14
It happened to me as well when trying to update several packages. I tried updating each package individually but got the same result each time. My issue was also corrected by replacing `yay-git` with `yay`.

```
 % yay -Syu                                                                                                                                                                                                                                                               
[sudo] password for dcaiafa: 
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: 4 Packages to upgrade.
4  aur/google-chrome  107.0.5304.110-1      -> 108.0.5359.124-1
3  aur/slack-desktop  4.29.144-1            -> 4.29.149-1
2  aur/yay-git        11.3.1.r60.g7612bb5-1 -> 11.3.1.r92.gc40e949-1
1  aur/zoom           5.12.6-1              -> 5.13.3-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:4]  google-chrome-108.0.5359.124-1  slack-desktop-4.29.149-1  yay-git-11.3.1.r92.gc40e949-1  zoom-5.13.3-1

  4 google-chrome                            (Installed) (Build Files Exist)
  3 slack-desktop                            (Installed) (Build Files Exist)
  2 yay-git                                  (Installed) (Build Files Exist)
  1 zoom                                     (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (4/0): google-chrome, slack-desktop, yay-git, zoom
  4 slack-desktop                            (Installed) (Build Files Exist)
  3 yay-git                                  (Installed) (Build Files Exist)
  2 zoom                                     (Installed) (Build Files Exist)
  1 google-chrome                            (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/4) Parsing SRCINFO: slack-desktop
:: (2/4) Parsing SRCINFO: yay-git
:: (3/4) Parsing SRCINFO: zoom
:: (4/4) Parsing SRCINFO: google-chrome
==> Making package: slack-desktop 4.29.149-1 (Mon 09 Jan 2023 09:30:16 AM PST)
==> Retrieving sources...
  -> Found slack-desktop-4.29.149-amd64.deb
==> Making package: google-chrome 108.0.5359.124-1 (Mon 09 Jan 2023 09:30:16 AM PST)
  -> Found slack-desktop.patch
==> Retrieving sources...
==> Making package: zoom 5.13.3-1 (Mon 09 Jan 2023 09:30:16 AM PST)
==> Validating source files with b2sums...
    slack-desktop-4.29.149-amd64.deb ... ==> Retrieving sources...
  -> Found google-chrome-stable_108.0.5359.124-1_amd64.deb
  -> Found zoom-5.13.3.651_orig_x86_64.pkg.tar.xz
  -> Found eula_text.html
==> Validating source files with sha512sums...
    zoom-5.13.3.651_orig_x86_64.pkg.tar.xz ...   -> Found google-chrome-stable.sh
==> Validating source files with sha512sums...
    google-chrome-stable_108.0.5359.124-1_amd64.deb ... Passed
    slack-desktop.patch ... Passed
Passed
    eula_text.html ... Passed
    google-chrome-stable.sh ... Passed
Passed
==> Making package: yay-git 11.3.1.r92.gc40e949-1 (Mon 09 Jan 2023 09:30:18 AM PST)
==> Retrieving sources...
  -> Updating yay git repo...
==> Validating source files with sha256sums...
    yay ... Skipped
==> Making package: google-chrome 108.0.5359.124-1 (Mon 09 Jan 2023 09:30:19 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found google-chrome-stable_108.0.5359.124-1_amd64.deb
  -> Found eula_text.html
  -> Found google-chrome-stable.sh
==> Validating source files with sha512sums...
    google-chrome-stable_108.0.5359.124-1_amd64.deb ... Passed
    eula_text.html ... Passed
    google-chrome-stable.sh ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting google-chrome-stable_108.0.5359.124-1_amd64.deb with bsdtar
==> Sources are ready.
==> Making package: google-chrome 108.0.5359.124-1 (Mon 09 Jan 2023 09:30:20 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
 -> google-chrome-108.0.5359.124-1 already made -- skipping build
==> Making package: slack-desktop 4.29.149-1 (Mon 09 Jan 2023 09:30:21 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found slack-desktop-4.29.149-amd64.deb
  -> Found slack-desktop.patch
==> Validating source files with b2sums...
    slack-desktop-4.29.149-amd64.deb ... Passed
    slack-desktop.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
==> Sources are ready.
==> Making package: slack-desktop 4.29.149-1 (Mon 09 Jan 2023 09:30:23 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
 -> slack-desktop-4.29.149-1 already made -- skipping build
==> Making package: yay-git 11.3.1.r92.gc40e949-1 (Mon 09 Jan 2023 09:30:25 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating yay git repo...
==> Validating source files with sha256sums...
    yay ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of yay git repo...
Cloning into 'yay'...
done.
Switched to a new branch 'makepkg'
==> Starting pkgver()...
==> Sources are ready.
==> Making package: yay-git 11.3.1.r92.gc40e949-1 (Mon 09 Jan 2023 09:30:31 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
 -> yay-git-11.3.1.r92.gc40e949-1 already made -- skipping build
 -> Found git repo: github.com/Jguer/yay.git
==> Making package: zoom 5.13.3-1 (Mon 09 Jan 2023 09:30:32 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found zoom-5.13.3.651_orig_x86_64.pkg.tar.xz
==> Validating source files with sha512sums...
    zoom-5.13.3.651_orig_x86_64.pkg.tar.xz ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting zoom-5.13.3.651_orig_x86_64.pkg.tar.xz with bsdtar
==> Starting prepare()...
==> Sources are ready.
==> Making package: zoom 5.13.3-1 (Mon 09 Jan 2023 09:30:41 AM PST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
 -> zoom-5.13.3-1 already made -- skipping build
```

**Comment by Jguer** [comment] 2023-02-21 02:38
Closing as I'm unable to reproduce, `yay-git` has seen a bunch of updates, let's create a new issue if it isn't fixed

**Closed as completed by Jguer** 2023-02-21 02:38 UTC
Labels: Type: Bug, Status: Cannot Reproduce
