### ISSUE TITLE
feature request: Apply patches to PKGBUILD via CLI

### ISSUE THREAD

**Issue by NobbZ** [Jguer/yay#543] opened 2018-07-11 08:39 UTC
I have some machines where I am doing a scripted setup.

Also I want to use ``yay`` to manage AUR installations as it is much easier than to resolve dependencies by hand.

But there is an AUR package where I need to apply a path to a pkgbuild before beeing able to install it at all.

Is there a way to apply this patch via the CLI or do I need to checkout, apply, makepkg, pacman -U for that package manually?

**Comment by Morganamilo** [comment] 2018-07-11 09:40
If you go to the pkgbuild cache and apply the patch there and commit, it will stick for future updates and will be merged with updates from the AUR.

**Comment by Jguer** [comment] 2018-07-12 09:43
Possibly mergeable with #336

**Comment by Morganamilo** [comment] 2018-07-19 16:48
Yep I'm going to close this as a duplicate of #336.

**Closed by Morganamilo** 2018-07-19 16:48 UTC
Labels: feature request
