### ISSUE TITLE
yay --clean bug

### ISSUE THREAD

**Issue by IamRezaMousavi** [Jguer/yay#2062] opened 2023-04-04 01:48 UTC
I can't clean my system :(

![Screenshot from 2023-04-04 05-11-55](https://user-images.githubusercontent.com/83984878/229664939-89b316d3-73bc-4eb6-90d9-72a72f718bb1.png)

**Comment by kanna5** [comment] 2023-04-04 04:29
Try `yay -Y --clean`

**Comment by kolayne** [comment] 2023-04-04 10:24
The workaround worked for me

**Comment by IamRezaMousavi** [comment] 2023-04-04 21:37
> Try `yay -Y --clean`

It's worked for me

But empty `--clean` command  still has a bug

**Comment by IamRezaMousavi** [comment] 2023-04-04 22:14
is this command use `sudo pacman -Qtdq | sudo pacman -Rns -` too??
(for cleaning all unnecessary packages in system)

**Comment by Jguer** [comment] 2023-04-05 08:17
closing as intended change https://github.com/Jguer/yay/releases/tag/v12.0.0 

duplicate of https://github.com/Jguer/yay/issues/2049

**Closed as completed by Jguer** 2023-04-05 08:17 UTC
Labels: Type: Bug, Status: Triage
