### ISSUE TITLE
No output for operations without arguments or for non-existing operations/options

### ISSUE THREAD

**Issue by AlexWayfer** [Jguer/yay#400] opened 2018-05-09 19:51 UTC
#### Affected Version

`yay v6.727`

#### Issue

There is no output for operations without arguments, or for non-existing operations/options. It's strange.

#### Steps to reproduce

```
> sudo pacman -R
error: no targets specified (use -h for help)
> yay -R
error: no targets specified (use -h for help)
> sudo pacman -S
error: no targets specified (use -h for help)
> yay -S
> yay -Y
> yay -P
> yay -G
:: Querying AUR...
> yay -V
yay v6.727
> yay -v
> yay -w
> yay --non-existing
>
```

**Comment by Morganamilo** [comment] 2018-05-09 21:10
Duplicate of #307.

**Closed by Morganamilo** 2018-05-09 21:10 UTC

**Comment by AlexWayfer** [comment] 2018-05-09 21:12
Sorry!
