### ISSUE TITLE
Update flatpaks when updating pacman and aur packages

### ISSUE THREAD

**Issue by elaine-jackson** [Jguer/yay#1798] opened 2022-08-20 15:35 UTC
### Is your feature request related to a problem? Please describe.

When performing system updates, currently I have to first run yay's updater (`yay -Syu`) then run flatpak updates. It would be nice if yay could automatically do this for me.

### Describe the solution you'd like

Yay will search if flatpak is installed and run `flatpak update` command if it is anytime a user runs `yay -Syu`.

### Describe alternatives you've considered
Running `flatpak update` after running `yay -Syu`

### Additional context

N/A

**Comment by grandchild** [comment] 2022-08-22 11:38
Hi, this is a duplicate of #649 -- please see there for discussion, and please search _all_ issues before opening a new one, thank you!

**Closed as not planned** 2022-08-22 11:39 UTC
Labels: Type: Feature Request, Status: Out of Scope

**Comment by grandchild** [comment] 2022-08-22 11:43
Additional hint: It's generally _highly_ recommended to just add your own little alias like
```shell
alias up='yay ; flatpak update'
```
to your shell's `.*rc` file for things like this. It's just one tiny line of code, it does exactly what you want, and `yay` doesn't have to maintain(!) tens, possibly hundreds, of lines of code to do things that it wasn't built for.
