### ISSUE TITLE
A weird so-called CGo Bug during makepkg yay.

### ISSUE THREAD

**Issue by arkimium** [Jguer/yay#2365] opened 2024-01-29 00:32 UTC
### Affected Version

No yay version. But yay-git's version instead.
`yay-git 10.1.0.r3.g7d080df-1`. No libalpm version. (Idk if libalpm was missed during I found this bug.)

### Describe the bug

Hi there from Lyen.
I have a question for my first time _**using yay to install HYPRLAND for my Arch Linux. **_
Yes, it is. I used it for only install a dynamic GNU. 
The author, [Soldoestech](https://github.com/SolDoesTech) firstly made and installed yay before install hyprland. But unfortunately, my workspace's HQ is in **CHINA**, NOT the US or other overseas area, so our network may blocked github and We are also looking for alternatives (ie. Gitee), ~~But in the end we still rely on go-alpm from . 
Copilot adviced me use Goproxy, but still didnt work. In fact, There are no errors in the previous compilation,~~ (PS. We modified PKGBUILD and changed to Gitee Repo, and the previous stage done.) But there seems to be an error in the place of `handle.go` suddenly. It said-most people forget to remember the two error codes are-`C.alpm_option_set_arch` and `C.alpm_option_get_arch`. The "get" error was received in 430 ports of the go-alpm page, and another was received in 436 ports. GitHub Copilot said it should be a problem from Binding of Go and C. It means this is a CGo Problem?! It's weird I think. This problem was appeared when execute `makepkg -si`. This is the screenshot.
![1706448416778.jpg](https://github.com/Jguer/yay/assets/114994536/94387532-b5dd-432d-985b-e37901bccca3)

I hope we can try our best to solve this problem. So can you give me an advice for me? THX :-).
btw my arch linux is **tty** mode with git & neovim (nano has been installed in it), meaning that i executed minimal installation without any additional pkgs expect git and neovim.

Lyen
Sent at 8:32 am BJT
1.29.24

### Reproduction Steps
```sh
[segkurny@archlinux yay-git]$ makepkg -si
==> Making package: yay-git 10.1.0.r3.g7d080df-1 (Mon 29 Jan 2024 07:59:27 AM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving Sources...
    -> Updating yay git repo...  // That is the resolution I tried to use Goprpxy.
==> Vaildating source files with sha256sums...
       yay... Skipped
==> Extracting sources...
    -> Creating working copy of yay git repo...
Reset branch 'makepkg'   // The bug was appeared at below.
==> Starting pkgver()...
Removing existing $pkgdir/ directory...
==> Starting build()...
go build -v -trimpath -mod=readonly -modcacherw -ldflags '-s -w -Wl,-01,--sort-common,--as-needed,-z,now -X "main.yayVersion=10.0.r3.g7d080df" -X "main.localePath=/usr/share/locale"' -biuldmode=pie -o yay
github.com/Jguer/go-alpm/v2
# github.com/Jguer/go-alpm/v2
../gopath/pkg/mod/github.com/!juger/go-aplm/v2@v2.0.1/handle.go:430:10: could not determine kind of name for C.alpm_option_get_arch
../gopath/pkg/mod/github.com/!juger/go-alpm/v2@v2.0.1/handle.go:436:10: could not determine kind of name for C.alpm_option_set_arch
make: *** [Makefile:127: yay] Error 1
==> ERROR: A failure occured in build().
       Aborting...
[segkurny@archlinux yay-git]$
```

### Expected behavior

Nothing much. Just install yay and Hyprland and made my Arch Linux dynamic and fantastic.
### Output

```sh
Sorry, cuz this bug was appeared in installing yay 
and unsucessful checked its version yet.
So no JSON output was generated.
```

**Comment by jdholtz** [comment] 2024-01-30 18:38
This seems to be a duplicate of https://github.com/Jguer/go-alpm/issues/49

**Comment by arkimium** [comment] 2024-05-05 15:47
> This seems to be a duplicate of https://github.com/Jguer/go-alpm/issues/49

I'm sorry I couldn't reply in time due to academic reasons. This problem was successfully fixed, and yay was installed on the host after I rebooted and re-entered this string of codes.
```sh
export GOPROXY=goproxy.io

# goproxy.cn instead.
```

**Closed as completed** 2024-05-05 15:47 UTC
Labels: Type: Bug, Status: Triage
