### ISSUE TITLE
Heroku-cli not upgradable

### ISSUE THREAD

**Issue by asrmarco13** [Jguer/yay#1363] opened 2020-09-08 10:26 UTC
#### Affected Version

yay v10.0.4 - libalpm v12.0.2

**Describe the bug**
When i try to upgrade heroku-cli from version 7.42.8-1 to 7.42.13-2 i receive the following error:

`==> Retrieving sources...`
`-> Downloading heroku-v7.42.13-linux-x64.tar.xz...`
 ` % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current`
 `  Dload  Upload   Total   Spent    Left  Speed`
`100 18.8M  100 18.8M    0     0  4456k      0  0:00:04  0:00:04 --:--:-- 4456k`
`==> Validating source_x86_64 files with sha256sums...`
 `   heroku-v7.42.13-linux-x64.tar.xz ... FAILED`
`==> ERROR: One or more files did not pass the validity check!`
`error downloading sources: heroku-cli`

**To Reproduce**
`yay -Syu heroku-cli`

**Expected behavior**
Update of heroku-cli.

**Output**
My current yay config:

`{`
        `"aururl": "https://aur.archlinux.org",`
        `"buildDir": "/home/marcoorfei/.cache/yay",`
      `  "absdir": "/home/marcoorfei/.cache/yay/abs",`
       ` "editor": "",`
        `"editorflags": "",`
        `"makepkgbin": "makepkg",`
       ` "makepkgconf": "",`
       ` "pacmanbin": "pacman",`
       ` "pacmanconf": "/etc/pacman.conf",`
      `  "redownload": "no",`
       ` "rebuild": "no",`
       ` "answerclean": "",`
       ` "answerdiff": "",`
       ` "answeredit": "",`
       ` "answerupgrade": "",`
       ` "gitbin": "git",`
       ` "gpgbin": "gpg",`
       ` "gpgflags": "",`
       ` "mflags": "",`
       ` "sortby": "votes",`
        `"searchby": "name-desc",`
       ` "gitflags": "",`
       ` "removemake": "ask",`
       ` "sudobin": "sudo",`
      `  "sudoflags": "",`
      `  "requestsplitn": 150,`
       ` "sortmode": 0,`
       ` "completionrefreshtime": 7,`
        `"sudoloop": false,`
        `"timeupdate": false,`
        `"devel": false,`
        `"cleanAfter": false,`
        `"provides": true,`
        `"pgpfetch": true,`
        `"upgrademenu": true,`
        `"cleanmenu": true,`
        `"diffmenu": true,`
        `"editmenu": false,`
        `"combinedupgrade": false,`
        `"useask": false,`
        `"batchinstall": false`
`}`

**Comment by JojiiOfficial** [comment] 2020-09-08 11:12
The problem is not yay, but the PKGBUILD (the "aur package") itself. You can either download the PKGBUILD and upgrade its validation hashsums or wait for the maintainer to do so.

**Comment by grandchild** [comment] 2020-09-08 12:44
@asrmarco13 if this helped you, then please close the issue, thank you! :)

**Closed as completed** 2020-09-08 12:47 UTC
Labels: Type: Bug, Status: Triage
