### ISSUE TITLE
One AUR package failing result in skipping the other one, even when unrelated.

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#1089] opened 2019-10-24 00:41 UTC
#### Affected Version
yay v9.4.0 - libalpm v12.0.0

#### Issue
When updating several AUR packages, if one of the builds fails, yay skips the other packages, even if those are unrelated (not depending on the one that failed to build).

It should build the other packages if unrelated to the failing one (the only reason I see not doing it is to see the build's failure logs; solution I see to that are to either have an option to continue the other packages if one fails (didn't see any for that), or to record output of package creation and then show it again at the end (or write it in a file, which in itself could be useful to study package creation errors).

**Comment by Jguer** [comment] 2019-10-24 11:28
Duplicate of
https://github.com/Jguer/yay/issues/548

**Closed by Jguer** 2019-10-24 11:28 UTC
