### ISSUE TITLE
==> ATTENTION: PACKAGER must be in the format "Example name <address@email.no valid>"

### ISSUE THREAD

**Issue by medioman** [Jguer/yay#1097] opened 2019-10-24 21:40 UTC
#### Affected Version

Hi,after installing the last pacman this sentence came out with yay and yaourt
#### Issue

<indirizzo@email.nonvalido>'
==> Creazione del pacchetto: yay 9.4.2-1 (gio 24 ott 2019, 23:16:21)
==> Download dei sorgenti in corso...
  -> Download di yay-9.4.2.tar.gz in corso...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: github.com
Warning: Transient problem: timeout Will retry in 3 seconds. 3 retries left.
100   117    0   117    0     0     21      0 --:--:--  0:00:05 --:--:--    23
100  351k  100  351k    0     0  55290      0  0:00:06  0:00:06 --:--:--  327k
==> Validazione di source file con sha1sums...
    yay-9.4.2.tar.gz ... Verificato
==> Pulizia in corso...
==> ATTENZIONE: PACKAGER deve essere nel formato 'Nome d'esempio <indirizzo@email.nonvalido>'
``

#### Steps to reproduce

1.
2.
3.

**Comment by Jguer** [comment] 2019-10-24 22:33
So it probably is not yay or yaourt
Duplicate of #1085

**Closed by Jguer** 2019-10-24 22:33 UTC
