### ISSUE TITLE
yay v12.0.0 tries massively to reinstall same versions of already installed packages

### ISSUE THREAD

**Issue by edmundlaugasson** [Jguer/yay#2055] opened 2023-04-03 16:38 UTC
### Affected Version

yay -V
yay v12.0.0 - libalpm v13.0.2

### Describe the bug

Updated as usual and after referred yay was installed, it starts to reinstall same versions of already installed AUR and also other packages ([one example](https://pastebin.com/Tim1wGKA)).

### Reproduction Steps

1. update yay to v12.0.0
2. update again with yay -Syyuu
3. it will offer to reinstall already installed packages

### Expected behavior

Only those packages are updated, which version is really updated.

### Output

```sh
yay -Pg
{
        "aururl": "https://aur.archlinux.org",
        "aurrpcurl": "https://aur.archlinux.org/rpc?",
        "buildDir": "/home/user/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "sudobin": "sudo",
        "sudoflags": "",
        "version": "12.0.0",
        "requestsplitn": 150,
        "completionrefreshtime": 7,
        "maxconcurrentdownloads": 0,
        "bottomup": true,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false,
        "batchinstall": false,
        "singlelineresults": false,
        "separatesources": true,
        "newinstallengine": true,
        "debug": false,
        "rpc": true
}
```
/etc/pacman.d/mirrorlist
```sh
# With:       reflector --verbose -c EE -c FI -c LV --protocol https --sort rate --latest 10 --save /etc/pacman.d/mirrorlist
# When:       2022-12-09 23:54:44 UTC
# From:       https://archlinux.org/mirrors/status/json/
# Retrieved:  2022-12-09 23:54:43 UTC
# Last Check: 2022-12-09 23:46:34 UTC

Server = https://arch.yhtez.xyz/$repo/os/$arch
Server = https://mirrors.xtom.ee/archlinux/$repo/os/$arch
Server = https://mirror.srv.fail/archlinux/$repo/os/$arch
```

**Comment by Jguer** [comment] 2023-04-03 16:42
Confirms https://github.com/Jguer/yay/pull/2054 as the root cause, releasing a patch version as soon as the CI is ready

EDIT: fixed in `yay-git` if you want to try it

**Closed as completed** 2023-04-03 17:07 UTC
Labels: Type: Bug, Status: Triage
