### ISSUE TITLE
"yay -Suy --devel --timeupdate" keeps reinstalling the same AUR packages

### ISSUE THREAD

**Issue by lowdown2infinity** [Jguer/yay#1251] opened 2020-04-23 09:08 UTC
#### Affected Version
yay v9.4.6.r0.g352667f - libalpm v12.0.1
#### Issue
When using `yay -Suy --devel --timeupdate` three AUR packages are being reinstalled every time without any change to the underlying git repositories:
```
3  aur/arch-silence-grub-theme-git  r7.cd4bba1-1         -> r7.cd4bba1-1
2  aur/brisk-menu-git               v0.6.1.r7.g19a6382-1 -> v0.6.1.r7.g19a6382-1
1  aur/pygtk                        2.24.0-12            -> 2.24.0-12
```

In total I am using ten AUR repositories. The other seven do not display this behavior. Here is the complete output of `yay -Y --gendb`

```
[e6430@arch ~]$ yay -Y --gendb
:: Querying AUR...
 -> Orphaned AUR Packages:  arch-silence-grub-theme-git
 -> Flagged Out Of Date AUR Packages:  intellij-idea-ce
:: PKGBUILD up to date, Skipping (1/10): intellij-idea-ce
:: PKGBUILD up to date, Skipping (2/10): childsplay-git
:: PKGBUILD up to date, Skipping (3/10): mate-tweak-git
:: PKGBUILD up to date, Skipping (4/10): pygtk
:: PKGBUILD up to date, Skipping (5/10): rclone-browser-git
:: PKGBUILD up to date, Skipping (6/10): arch-silence-grub-theme-git
:: PKGBUILD up to date, Skipping (7/10): brisk-menu-git
:: PKGBUILD up to date, Skipping (8/10): yay-git
:: PKGBUILD up to date, Skipping (9/10): visual-studio-code-bin
:: PKGBUILD up to date, Skipping (10/10): brother-mfc-l2710dn
:: Parsing SRCINFO (1/10): brother-mfc-l2710dn
:: Parsing SRCINFO (2/10): intellij-idea-ce
:: Parsing SRCINFO (3/10): mate-tweak-git
:: Parsing SRCINFO (4/10): pygtk
:: Parsing SRCINFO (5/10): rclone-browser-git
:: Parsing SRCINFO (6/10): yay-git
:: Parsing SRCINFO (7/10): arch-silence-grub-theme-git
:: Parsing SRCINFO (8/10): brisk-menu-git
:: Parsing SRCINFO (9/10): childsplay-git
:: Parsing SRCINFO (10/10): visual-studio-code-bin
==> Found git repo: github.com/kapitainsky/RcloneBrowser.git
==> Found git repo: github.com/fghibellini/arch-silence.git
==> Found git repo: github.com/getsolus/brisk-menu.git
==> Found git repo: github.com/ubuntu-mate/mate-tweak.git
==> Found git repo: github.com/Jguer/yay.git
==> Found git repo: git.savannah.nongnu.org/childsplay.git
==> GenDB finished. No packages were installed
```

#### Output
```
[e6430@arch ~]$ yay -Suy --devel --timeupdate
[sudo] password for e6430:
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
 -> Orphaned AUR Packages:  arch-silence-grub-theme-git
 -> Flagged Out Of Date AUR Packages:  intellij-idea-ce
:: 3 Packages to upgrade.
3  aur/arch-silence-grub-theme-git  r7.cd4bba1-1         -> r7.cd4bba1-1
2  aur/brisk-menu-git               v0.6.1.r7.g19a6382-1 -> v0.6.1.r7.g19a6382-1
1  aur/pygtk                        2.24.0-12            -> 2.24.0-12
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==>
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 3]  arch-silence-grub-theme-git-r7.cd4bba1-1  brisk-menu-git-v0.6.1.r7.g19a6382-1  pygtk-2.24.0-12

  3 arch-silence-grub-theme-git      (Installed) (Build Files Exist)
  2 brisk-menu-git                   (Installed) (Build Files Exist)
  1 pygtk                            (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: PKGBUILD up to date, Skipping (1/3): pygtk
:: PKGBUILD up to date, Skipping (2/3): brisk-menu-git
:: PKGBUILD up to date, Skipping (3/3): arch-silence-grub-theme-git
  3 arch-silence-grub-theme-git      (Installed) (Build Files Exist)
  2 brisk-menu-git                   (Installed) (Build Files Exist)
  1 pygtk                            (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
:: Parsing SRCINFO (1/3): arch-silence-grub-theme-git
:: Parsing SRCINFO (2/3): brisk-menu-git
:: Parsing SRCINFO (3/3): pygtk
==> Making package: arch-silence-grub-theme-git r7.cd4bba1-1 (Thu 23 Apr 2020 10:56:30 AM CEST)
==> Retrieving sources...
  -> Updating arch-silence git repo...
Fetching origin
==> Validating source files with sha512sums...
    arch-silence ... Skipped
==> Making package: brisk-menu-git v0.6.1.r7.g19a6382-1 (Thu 23 Apr 2020 10:56:33 AM CEST)
==> Retrieving sources...
  -> Updating brisk-menu git repo...
Fetching origin
==> Validating source files with sha1sums...
    brisk-menu ... Skipped
==> Making package: pygtk 2.24.0-12 (Thu 23 Apr 2020 10:56:35 AM CEST)
==> Retrieving sources...
  -> Found pygtk-2.24.0.tar.bz2
  -> Found 4aaa48eb80c6802aec6d03e5695d2a0ff20e0fc2.patch
  -> Found python27.patch
  -> Found fix-leaks-of-pango-objects.patch
==> Validating source files with md5sums...
    pygtk-2.24.0.tar.bz2 ... Passed
    4aaa48eb80c6802aec6d03e5695d2a0ff20e0fc2.patch ... Passed
    python27.patch ... Passed
    fix-leaks-of-pango-objects.patch ... Passed
==> Making package: arch-silence-grub-theme-git r7.cd4bba1-1 (Thu 23 Apr 2020 10:56:36 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating arch-silence git repo...
Fetching origin
==> Validating source files with sha512sums...
    arch-silence ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of arch-silence git repo...
Cloning into 'arch-silence'...
done.
==> Starting pkgver()...
==> Sources are ready.
==> Making package: arch-silence-grub-theme-git r7.cd4bba1-1 (Thu 23 Apr 2020 10:56:39 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
==> arch-silence-grub-theme-git-r7.cd4bba1-1 already made -- skipping build
==> Found git repo: github.com/fghibellini/arch-silence.git
[sudo] password for e6430:
loading packages...
warning: arch-silence-grub-theme-git-r7.cd4bba1-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) arch-silence-grub-theme-git-r7.cd4bba1-1

Total Installed Size:  0.28 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                                                                 [#######################################################################################] 100%
(1/1) checking package integrity                                                                                                               [#######################################################################################] 100%
(1/1) loading package files                                                                                                                    [#######################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [#######################################################################################] 100%
(1/1) checking available disk space                                                                                                            [#######################################################################################] 100%
:: Processing package changes...
(1/1) reinstalling arch-silence-grub-theme-git                                                                                                 [#######################################################################################] 100%
:: Running post-transaction hooks...
(1/1) Cleaning cache directory /var/cache/pacman/pkg...
==> Making package: brisk-menu-git v0.6.1.r7.g19a6382-1 (Thu 23 Apr 2020 10:56:46 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating brisk-menu git repo...
Fetching origin
==> Validating source files with sha1sums...
    brisk-menu ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of brisk-menu git repo...
Cloning into 'brisk-menu'...
done.
==> Starting pkgver()...
==> Sources are ready.
==> Making package: brisk-menu-git v0.6.1.r7.g19a6382-1 (Thu 23 Apr 2020 10:56:51 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
==> brisk-menu-git-v0.6.1.r7.g19a6382-1 already made -- skipping build
==> Found git repo: github.com/getsolus/brisk-menu.git
loading packages...
warning: brisk-menu-git-v0.6.1.r7.g19a6382-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) brisk-menu-git-v0.6.1.r7.g19a6382-1

Total Installed Size:  0.22 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                                                                 [#######################################################################################] 100%
(1/1) checking package integrity                                                                                                               [#######################################################################################] 100%
(1/1) loading package files                                                                                                                    [#######################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [#######################################################################################] 100%
(1/1) checking available disk space                                                                                                            [#######################################################################################] 100%
:: Processing package changes...
(1/1) reinstalling brisk-menu-git                                                                                                              [#######################################################################################] 100%
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Compiling GSettings XML schema files...
(3/4) Updating icon theme caches...
(4/4) Cleaning cache directory /var/cache/pacman/pkg...
==> Making package: pygtk 2.24.0-12 (Thu 23 Apr 2020 10:56:53 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found pygtk-2.24.0.tar.bz2
  -> Found 4aaa48eb80c6802aec6d03e5695d2a0ff20e0fc2.patch
  -> Found python27.patch
  -> Found fix-leaks-of-pango-objects.patch
==> Validating source files with md5sums...
    pygtk-2.24.0.tar.bz2 ... Passed
    4aaa48eb80c6802aec6d03e5695d2a0ff20e0fc2.patch ... Passed
    python27.patch ... Passed
    fix-leaks-of-pango-objects.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting pygtk-2.24.0.tar.bz2 with bsdtar
==> Starting prepare()...
patching file gtk/gtkmodule.c
Hunk #1 succeeded at 200 (offset -27 lines).
patching file gtk/pygtk.h
patching file gtk/gtk-2.10.defs
patching file pangocairo.override
patching file pango.defs
==> Sources are ready.
==> Making package: pygtk 2.24.0-12 (Thu 23 Apr 2020 10:56:57 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Sources are ready.
==> pygtk-2.24.0-12 already made -- skipping build
loading packages...
warning: pygtk-2.24.0-12 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) pygtk-2.24.0-12

Total Installed Size:  5.09 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                                                                 [#######################################################################################] 100%
(1/1) checking package integrity                                                                                                               [#######################################################################################] 100%
(1/1) loading package files                                                                                                                    [#######################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [#######################################################################################] 100%
(1/1) checking available disk space                                                                                                            [#######################################################################################] 100%
:: Processing package changes...
(1/1) reinstalling pygtk                                                                                                                       [#######################################################################################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Cleaning cache directory /var/cache/pacman/pkg...
```

**Comment by Jguer** [comment] 2020-04-27 17:46
duplicate of https://github.com/Jguer/yay/issues/947

**Closed by Jguer** 2020-04-27 17:46 UTC
