### ISSUE TITLE
Yay broken after upgrading pacman on Arch Linux 03152024

### ISSUE THREAD

**Issue by BowenWang** [Jguer/yay#2397] opened 2024-03-15 23:54 UTC
### Reproduction Steps

1.  Run `pacman -Syu` to upgrade software in Arch Linux's repo.
2. Then run `yay -Syu` to upgrade software in AUR
3. Error message said "error while loading shared libraries: libalpm.so.13: cannot open shared object file: No Such file or directory"

### Output
yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory.

**Comment by Jguer** [comment] 2024-03-16 00:26
closed as duplicate of https://github.com/Jguer/yay/issues/2393

**Closed as completed by Jguer** 2024-03-16 00:26 UTC
Labels: Type: Bug, Status: Duplicate
