### ISSUE TITLE
skip failing packages

### ISSUE THREAD

**Issue by moham96** [Jguer/yay#1126] opened 2019-11-27 08:51 UTC
#### Affected Version

 yay v9.4.2.r17.gb08e505b3422 - libalpm v12.0.1

#### Issue
When running an upgrade with `yay -Su` and one of the packages to be upgraded(or one of it's dependencies) fails to build, yay will quit and halt the whole upgrade process once it reaches the failing package.
it would be nice to have a flag to be used to tell yay to skip failing packages(if it's a dependency then don't bother building other dependencies of the package and skip it all together)
This would be very useful in scripts and auto-upgrade cronjobs

**Comment by LofhJann** [comment] 2019-12-05 10:46
Partial upgrade is not supported by Arch Linux, hence shouldn't be supported by yay in my opinion. Surely you could do partial upgrade by not installing failing packages, but in reality you should never do it.

https://wiki.archlinux.org/index.php/System_maintenance#Partial_upgrades_are_unsupported

**Comment by Morganamilo** [comment] 2019-12-05 16:41
Partial upgrades don't really apply to AUR packages.

**Comment by moham96** [comment] 2019-12-05 17:39
I agree with @Morganamilo, Since most AUR packages are built locally they will be linked to whatever libraries present on the system and it will not cause breakage.

**Comment by Evanlec** [comment] 2020-01-03 01:10
+1 please implement this feature for AUR packages.

I have an ever-increasing list of AUR packages in need of upgrade (20+) and it's very difficult to upgrade them all because inevitably one of them fails to build, stopping the entire show.
When this happens, it makes 0 progress as not even a single package gets upgraded, even if I use the --nobatchinstall flag, it will _build_ the packages one by one, but it's _Not_ installing them directly after building (even though the documentation states that it should), and thus when one package fails, nothing has been upgraded, and my only option is to upgrade them manually one at a time which is a gigantic PITA.

**Comment by C0D3D3V** [comment] 2020-04-11 15:41
Would be cool if yay would automatically restart with the package that failed as --ignore parameter.

**Comment by neumannjan** [comment] 2020-10-02 10:45
+1 agree with @Morganamilo . AUR packages are rarely dependent on each other, also the stability of your system rarely depends on AUR packages (because if it does, then you probably have to deal with much bigger update issues than just with missing partial update functionality). However, AUR packages do often fail to build and this halting updates for the rest of your packages makes no sense.

Therefore, I disagree with @LofhJann . Case in point: I doubt that the `tonelib-jam-bin` package failing to build will affect my `google-chrome` package in any negative way. :wink:

**Comment by odinu** [comment] 2021-04-21 09:22
I also got here because of `tonelib-jam-bin` :smile: For this package at least I know it can never update so I can skip it every time I run yay, but for others that might sometimes work it's a guessing game, and it takes half an hour of building something until it fails, just to have to exclude it and run everything again ...until something else fails.

**Comment by hockeymikey** [comment] 2021-05-15 06:05
This needs to be a feature. I just ignore the failed package by removing it from my upgrade arguments and continue on my way. There's no reason not to automate that, it's completely optional for the user to use and just gives people more freedom to manage their machines how they see fit.

**Comment by DocMAX** [comment] 2021-07-24 07:53
I want skip on errors option too

**Comment by Jguer** [comment] 2021-08-31 00:32
Closing as duplicate of https://github.com/Jguer/yay/issues/848

**Closed by Jguer** 2021-08-31 00:32 UTC
Labels: Type: Enhancement, Status: Approved
