### ISSUE TITLE
sudo timeouts even with sudoloop

### ISSUE THREAD

**Issue by ruro** [Jguer/yay#1379] opened 2020-10-03 04:05 UTC
#### Affected Version

```
yay v10.0.4 - libalpm v12.0.2
```

**Describe the bug**
`sudo` timeouts during a system update (`yay -Suy`)
During the download & install process, you can see these messages between the progress logging lines:
```
(295/392) upgrading mkinitcpio                                                                           [##############################################################] 100%

sudo: timed out reading password
(296/392) upgrading linux54                                                                              [######################----------------------------------------]  36%
[sudo] password for user: (296/392) upgrading linux54                                                                              [#########################-----------------(296/392) upgrading linux54                                                                              [##############################################################] 100%
```
In fact, I think it timed out so many times, that I got temporarily locked out of my account.

The timeouts were happening even during the ABS part of the update.
Note, that I have the `sudoloop` option enabled. I thought, that it was supposed to remember the initial `sudo` password. 

**Expected behavior**
I expected the `sudoloop` to keep my initial `sudo` session alive or at least only prompt me for my password, when `yay` is waiting and not printing anything, so that the `[sudo] password for user:` prompt is not lost among the logs.

**Output**

`yay -Pg` output:
```
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/user/.cache/yay",
	"absdir": "/home/user/.cache/yay/abs",
	"editor": "vim",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "/etc/makepkg.conf",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": true,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": true,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": true
}
```

**Comment by Morganamilo** [comment] 2020-10-03 08:13
Have you edited how long sudo remembers passwords for or any other settings?

**Comment by ruro** [comment] 2020-10-03 15:07
Afaik, I didn't change any timeout-related sudo settings. The contents of my `sudoers` and `sudoers.d/*` seem to only contain permissions-related configuration.

Are there any other mechanisms to change sudo settings apart from these files?

**Comment by ruro** [comment] 2020-12-02 16:28
The issue is not fixed, it's still happening with
```
yay v10.1.0 - libalpm v12.0.2
```

**Comment by ruro** [comment] 2021-01-31 16:56
The issue is not fixed yet, afaik. If you need my help with this issue, feel free to ask.

**Comment by Jguer** [comment] 2021-02-01 08:04
I can't reproduce this issue unfortunately. 

Can you do `whereis sudo` just to confirm there's no wrappers on sudo?

Also, you could try setting your timeout to the default 5min and trying again to verify it's really unrelated to the sudo timeout

**Comment by ruro** [comment] 2021-02-01 12:59
> Can you do `whereis sudo` just to confirm there's no wrappers on sudo?

`whereis sudo` prints `sudo: /usr/bin/sudo /usr/lib/sudo /etc/sudo.conf /usr/share/man/man8/sudo.8.gz`.
`sudo --version` is
```
Sudo version 1.9.5p2
Sudoers policy plugin version 1.9.5p2
Sudoers file grammar version 48
Sudoers I/O plugin version 1.9.5p2
Sudoers audit plugin version 1.9.5p2
```

> Also, you could try setting your timeout to the default 5min and trying again to verify it's really unrelated to the sudo timeout.

The output of `sudo grep "^[^#]" /etc/sudoers $(sudo find /etc/sudoers.d -type f)` (grepping all sudoers configuration files for non-comment lines) is:

```
/etc/sudoers:root ALL=(ALL) ALL
/etc/sudoers: %wheel ALL=(ALL) ALL
/etc/sudoers.d/20-cpupower:ruro ALL=(root) NOPASSWD: /usr/bin/cpupower-performance
/etc/sudoers.d/20-cpupower:ruro ALL=(root) NOPASSWD: /usr/bin/cpupower-powersave
/etc/sudoers.d/20-cpupower:ruro ALL=(root) NOPASSWD: /usr/bin/cpupower-info
/etc/sudoers.d/20-notimeout:Defaults passwd_timeout=0
/etc/sudoers.d/ctdb:Defaults!/etc/ctdb/statd-callout	!requiretty
/etc/sudoers.d/ctdb:rpcuser		ALL=(ALL) 	NOPASSWD: /etc/ctdb/statd-callout
/etc/sudoers.d/20-tops:ruro ALL=(root) NOPASSWD: /usr/bin/iotop
/etc/sudoers.d/20-tops:ruro ALL=(root) NOPASSWD: /usr/bin/htop
/etc/sudoers.d/20-tops:ruro ALL=(root) NOPASSWD: /usr/bin/swapoff
/etc/sudoers.d/20-tops:ruro ALL=(root) NOPASSWD: /usr/bin/swapon
/etc/sudoers.d/20-tops:ruro ALL=(root) NOPASSWD:SETENV: /usr/bin/filelight
```

As you can see, the value of `timestamp_timeout` is never changed (the default is already 5 according to `man sudoers`). Do you want me to set it explicitly anyway or what?

Btw, `passwd_timeout=0` was added by me after this issue started happening. It makes it so that the sudo prompt itself never timeouts (by default, not entering anything into the sudo prompt for 5 minutes counts as a failed attempt). This shouldn't affect the timestamp timeout duration.

---

P.S. I tried looking at the sudo loop code myself, and it seems to me that it just sleeps a static 298 seconds between `sudo -v` execs. 298 is just 2 seconds less than the 5-minute timeout period. Do you think, that the 2 second buffer could just be not enough.

1) Maybe the machine just actually lags for 2 whole seconds, when under heavy load. 2 seconds is quite a lot, but maybe such a lag spike is possible, if all the cores are occupied with compiling something or writing stuff to disk when installing a big package.
2) I am not too familiar with how go goroutines work, but if I understood it correctly (?), each goroutine doesn't have its own thread, but rather they share a common async thread pool. Maybe there is some thread resource contention where the sudo loop goroutine execution gets delayed due to other goroutines.
3) Again, I am not too familiar with go, but there are 2 potentially suspicious details of `time.Sleep`:
     - The documentation says that `time.Sleep` "pauses the current goroutine for **at least the duration d**" (emphasis mine) so maybe "at least 298 seconds" sometimes results in 300+ seconds of actual sleep.
     - Do you know, which clock does `time.Sleep` use as a reference? There could be some weird wall clock vs monotonic/cpu clock shenanigans going on, eating the 2 second buffer. It seems to me, that `sudo` uses the monotonic clock for timestamps, while `time.Sleep` uses the wall clock. (Edit: nvm, after some more research, `time.Sleep` also seems to use the monotonic clock)

**Comment by ulidtko** [comment] 2021-02-09 12:20
I'm affected by this too. Getting locked out is **not fun**.

![image](https://user-images.githubusercontent.com/365338/107361998-dee99280-6ae0-11eb-94bc-2e7ed058e05c.png)

<details><summary>Configs, versions elaborated (<i>click to expand</i>)</summary>

My Yay config is pretty much the same as @RuRo, `sudoloop` is set.

```
$ sudo --version
Sudo version 1.9.5p2
Sudoers policy plugin version 1.9.5p2
Sudoers file grammar version 48
Sudoers I/O plugin version 1.9.5p2
Sudoers audit plugin version 1.9.5p2
```
I've got no sudo wrappers (`which sudo` → `/usr/bin/sudo`) and its config is... utter defaults:
```
$ sudo grep "^[^#]" /etc/sudoers (sudo find /etc/sudoers.d -type f)
/etc/sudoers:root ALL=(ALL) ALL
/etc/sudoers:%adm ALL=(ALL) ALL
/etc/sudoers.d/ctdb:Defaults!/etc/ctdb/statd-callout	!requiretty
/etc/sudoers.d/ctdb:rpcuser		ALL=(ALL) 	NOPASSWD: /etc/ctdb/statd-callout
```
Yay version is current latest, `yay v10.1.2 - libalpm v12.0.2`.

</details>


The findings of @RuRo make perfect sense:
https://github.com/Jguer/yay/blob/7d849a8dec4e787cdd1fb0adade7074e53d42f28/exec.go#L22-L27

2-second margin is way too low. @Jguer this code basically creates a race (that's why you have difficulties reproducing it):
 * The period T of the loop (time between `sudo -v` revalidations) will be T ≥ 298s; i.e. T = 298s + E where E is machine- and workload-dependent, random, accumulated scheduling delay. Remember that even starting a process (e.g. `sudo`) takes time — that time counts towards E. Whenever this E exceeds 2 seconds — we lose the race and start getting the password prompt.

This fix for this can be crushingly trivial and no-risk. Size up the margin.
```diff
diff --git i/exec.go w/exec.go
index fd63dcf..ad6bbde 100644
--- i/exec.go
+++ w/exec.go
@@ -22,7 +22,9 @@ func sudoLoopBackground() {
 func sudoLoop() {
        for {
                updateSudo()
-               time.Sleep(298 * time.Second)
+               time.Sleep(240 * time.Second)
        }
 }
 ```
BTW, I'd also advise adding a comment mentioning that the magic constant is based on sudo's default timestamp invalidation period (5 minutes).

**Comment by Jguer** [comment] 2021-03-11 08:32
@ulidtko nice find, yes, this might be a better solution

**Comment by ulidtko** [comment] 2021-03-11 12:18
@Jguer I mean... there's literally 0 chance to break anything with such a change. Why don't you simply tweak the timeout? Do you need a PR to merge for this?

**Comment by grandchild** [comment] 2021-03-11 15:45
> there's literally 0 chance to break anything with such a change

![linus-oneliner-changes](https://user-images.githubusercontent.com/770029/110813840-294d6300-8289-11eb-8c14-74801a8fddac.gif)

**Comment by ulidtko** [comment] 2021-03-12 13:21
@grandchild cool, thanks for reminding Yay has a test suite. I've reviewed it, and determined that it can't break from reducing the timeout as above. Nevertheless, I've built & run it, just to not fool myself as in the Linus's irony. An unrelated test fails on master:
```
=== RUN   TestPrintNewsFeed/all-verbose
    news_test.go:118: snapshot not equal:
        --- Previous
        +++ Current
        @@ -36,3 +36,3 @@
         
        -2020-02-22 Planet Arch Linux migration
        +2020-02-23 Planet Arch Linux migration
         The software behind planet.archlinux.org was implemented in Python 2 and is no longer maintained upstream. This functionality has now been implemented in archlinux.org's archweb backend which is actively maintained but offers a slightly different experience.
        
=== RUN   TestPrintNewsFeed/all-quiet
    news_test.go:118: snapshot not equal:
        --- Previous
        +++ Current
        @@ -4,3 +4,3 @@
         2020-02-17 sshd needs restarting after upgrading to openssh-8.2p1
        -2020-02-22 Planet Arch Linux migration
        +2020-02-23 Planet Arch Linux migration
         2020-02-24 The Future of the Arch Linux Project Leader
        
--- FAIL: TestPrintNewsFeed (0.01s)
    --- FAIL: TestPrintNewsFeed/all-verbose (0.00s)
    --- FAIL: TestPrintNewsFeed/all-quiet (0.00s)
    --- PASS: TestPrintNewsFeed/latest-quiet (0.00s)
    --- PASS: TestPrintNewsFeed/latest-quiet-topdown (0.00s)
```

Exact same test report with the suggested change applied.

I mean... the gif totally has a valid point, and *in general* I agree with its sentiment, good one. However you can't laugh off the details here.

The details: we have at least 2 users annoyed enough to report the sudoloop randomly breaking. We have maintainer can't repro. We have a model explanation of how both those things can happen (an instability; losing the time race once due to heavy-loaded/slow machine leads to the whole loop breaking). Per that model, kicking up the race-winning chance by several 9s should crush the issue.

Just to show I'm not pushing a single-minded poorly thought-through idea. There are of course downsides to reducing the timeout: extra process calls, extra load & energy spent, extra audit logs, a tiny bit more SSD wear. For those reasons, cutting that timeout down all the way to 5-10 seconds isn't wise. So I'm suggesting a 20/80 split as a decent balance.

**Comment by Jguer** [comment] 2021-03-13 11:01
It should be fine, I'm pushing the patch with 240s, I'll definitely hear if it's not fine

**Closed as completed** 2021-03-13 11:08 UTC
Labels: Type: Bug, Status: Triage
