### ISSUE TITLE
Searching in AUR via SOCKS proxy does not work

### ISSUE THREAD

**Issue by muffl0n** [Jguer/yay#795] opened 2018-11-08 08:17 UTC
#### Affected Version
yay v8.1173.0 - libalpm v11.0.1

#### Issue
Updating the "package database" via SOCKS proxy works, searching for package (in AUR) doesn't.

##### SOCKS proxy
```
export http_proxy=socks5h://localhost:9191
export https_proxy=socks5h://localhost:9191
```

```
yay -Syy
:: Synchronizing package databases...
 core                           135.7 KiB  4.91M/s 00:00 [#############################] 100%
 extra                         1642.9 KiB  8.02M/s 00:00 [#############################] 100%
 community                        4.6 MiB  8.16M/s 00:00 [#############################] 100%
 archlinuxfr                     11.4 KiB  1142K/s 00:00 [#############################] 100%```
```
```
yay -Ss mattermost
community/matterbridge 1.11.1-1 (4.6 MiB 25.3 MiB)
    Multi-protocols (IRC/XMPP/Mattermost/Slack/Matrix/etc) bridge
Error during AUR search: Get https://aur.archlinux.org/rpc.php?arg=mattermost&type=search&v=5: proxyconnect tcp: dial tcp: lookup socks5h: Temporary failure in name resolution
Showing Repo packages only
```
yaourt works, though
```
yaourt -Ss mattermost                                                     
community/matterbridge 1.11.3-1
    Multi-protocols (IRC/XMPP/Mattermost/Slack/Matrix/etc) bridge
[...]
aur/python-mattermostdriver 2.1.1-2 (Out of Date) (1) (0.00)
    A Python Mattermost Driver
```
##### HTTP proxy
```
export http_proxy=http://foo:bar@myproxy:8080
export https_proxy=http://foo:bar@myproxy:8080
```

```
yay -Syy
:: Synchronizing package databases...
 core                           135.7 KiB  18.9M/s 00:00 [#############################] 100%
 extra                         1642.9 KiB   134K/s 00:00 [#############################] 100%
 community                        4.6 MiB  7.54M/s 00:00 [#############################] 100%
 archlinuxfr                     11.4 KiB  1359K/s 00:00 [#############################] 100%```
```

```
yay -Ss mattermost
aur/purple-mattermost-spectrum2 v1.2.r1.daf5d6b-1 (+0 0.00%)
    A purple-based (Pidgin) plugin for Mattermost. (spectrum2 work)
[...]
aur/mattermost-desktop 4.1.2-2 (+40 2.91%) 
    Mattermost Desktop application for Linux (Beta)
community/matterbridge 1.11.3-1 (5.4 MiB 27.4 MiB) 
    Multi-protocols (IRC/XMPP/Mattermost/Slack/Matrix/etc) bridge
```

#### Output
yay -Pg:
```
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/svs/.cache/yay",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "tarbin": "bsdtar",
        "redownload": "no",
        "rebuild": "no",
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "gitflags": "",
        "removemake": "ask",
        "requestsplitn": 150,
        "sortmode": 0,
        "completionrefreshtime": 7,
        "sudoloop": false,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "gitclone": true,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": true,
        "editmenu": false,
        "combinedupgrade": false,
        "useask": false
}
```

**Comment by muffl0n** [comment] 2018-11-08 10:17
I've set up a docker container and tried gcc-go:
```
$ go version
go version go1.10.3 gccgo (GCC) 8.2.1 20180831 linux/amd64
$ gccgo --version
gccgo (GCC) 8.2.1 20180831
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ export | grep proxy
declare -x http_proxy="socks5h://localhost:9191"
declare -x https_proxy="socks5h://localhost:9191"
$ yay -Ss mattermost
community/matterbridge 1.11.3-1 (5.4 MiB 27.4 MiB) 
    Multi-protocols (IRC/XMPP/Mattermost/Slack/Matrix/etc) bridge
Error during AUR search: Get https://aur.archlinux.org/rpc.php?arg=mattermost&type=search&v=5: proxyconnect tcp: dial tcp: lookup socks5h: Temporary failure in name resolution
Showing Repo packages only
```

**Comment by Jguer** [comment] 2018-11-08 10:29
Leaving here the only reference I can find to in the language https://github.com/golang/go/issues/13454

**Comment by Jguer** [comment] 2018-11-11 23:43
I linked that bug report but forgot to ask you, have you tried another protocol like `socks5://`?

**Comment by muffl0n** [comment] 2018-11-12 07:38
That's weird, now it fails the other way around. :D
```
export http_proxy=socks5://localhost:9191
export https_proxy=socks5://localhost:9191
```
```
-> % yay -Syy          
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from ftp.gwdg.de : Could not resolve host: ftp.gwdg.de
error: failed to update core (download library error)
error: failed retrieving file 'extra.db' from ftp.gwdg.de : Could not resolve host: ftp.gwdg.de
error: failed to update extra (download library error)
error: failed retrieving file 'community.db' from ftp.gwdg.de : Could not resolve host: ftp.gwdg.de
error: failed to update community (download library error)
error: failed retrieving file 'archlinuxfr.db' from repo.archlinux.fr : Could not resolve host: repo.archlinux.fr
error: failed to update archlinuxfr (download library error)
error: failed to synchronize all databases
```
```
$ yay -Ss mattermost
aur/purple-mattermost-spectrum2 v1.2.r1.daf5d6b-1 (+0 0.00%) 
    A purple-based (Pidgin) plugin for Mattermost. (spectrum2 work)
[...]
aur/mattermost-desktop 4.1.2-2 (+40 2.69%) 
    Mattermost Desktop application for Linux (Beta)
community/matterbridge 1.11.3-1 (5.4 MiB 27.4 MiB) 
    Multi-protocols (IRC/XMPP/Mattermost/Slack/Matrix/etc) bridge
```

yaourt fails completely:
```
% yaourt -Syy                                                     
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from ftp.gwdg.de : Could not resolve host: ftp.gwdg.de
error: failed to update core (download library error)
error: failed retrieving file 'extra.db' from ftp.gwdg.de : Could not resolve host: ftp.gwdg.de
error: failed to update extra (download library error)
error: failed retrieving file 'community.db' from ftp.gwdg.de : Could not resolve host: ftp.gwdg.de
error: failed to update community (download library error)
error: failed retrieving file 'archlinuxfr.db' from repo.archlinux.fr : Could not resolve host: repo.archlinux.fr
error: failed to update archlinuxfr (download library error)
error: failed to synchronize all databases
```
```
$ yaourt -Ss mattermost  
community/matterbridge 1.11.3-1
    Multi-protocols (IRC/XMPP/Mattermost/Slack/Matrix/etc) bridge
curl error: Couldn't resolve host name
```

To avoid misunderstandings: I'm not able to resolve hosts without using either the socks- or the http-proxy. So looking up "repo.archlinux.fr", for example, fails but access via proxy works:
```
-> % curl -I repo.archlinux.fr
HTTP/1.1 200 OK
Date: Mon, 12 Nov 2018 07:36:47 GMT
Server: nginx/1.14.0
Content-Type: text/html
Proxy-Connection: Keep-Alive
```
Though curl fails if I set 
```
export http_proxy=socks5://localhost:9191
export https_proxy=socks5://localhost:9191
```

**Comment by Jguer** [comment] 2018-11-12 09:51
```
The proxy string may be prefixed with [scheme]:// to specify which kind of proxy is used. Use socks4://, socks4a://, socks5:// or socks5h:// (the last one to enable socks5 and asking the proxy to do the resolving, also known as CURLPROXY_SOCKS5_HOSTNAME type) to request the specific SOCKS version to be used. Otherwise SOCKS4 is used as default. 
```
Ok, so here is where I figure the problem is, curl supports all of these schemes, including socks5h which does the hostname resolution on the proxy side. Just from what I'm seeing I deduce:
- go resolves hostname even if it is just socks5, pacman does not (this is why your problem is reverted)
- go doesn't recognize socks5h and so fails proxying and pacman does recognize. (original problem)

If you're only running a localhost proxy server I would use the loopback address instead
```
export http_proxy=socks5://127.0.0.1:9191
export https_proxy=socks5://127.0.0.1:9191
```

If this still fails, We should take this opportunity to consider other vocations such as farming, mountain hiking or mule train wagoner so we can enjoy a simpler life where environment variables doesn't cause headaches every day. Either that or use `proxychains-ng` configured with only one proxy and yay compiled with gcc-go which should work because proxychains respects all protocols.

**Comment by muffl0n** [comment] 2018-11-12 10:13
I don't see any sense in changing "localhost" to "127.0.0.1" since "localhost" resolves to "127.0.0.1". It doesn't change anything in the behaviour I see.

Since I can reproduce this behaviour with this (my first :yum:) small go-Script I will just raise an issue upstream.
```
package main

import "net/http"
import "fmt"


func main() {
    resp, err := http.Get("http://example.com/")
    fmt.Println(resp, err)
}
```
```
<nil> Get http://example.com/: proxyconnect tcp: dial tcp: lookup socks5h: Temporary failure in name resolution
```

But regarding your ideas for other activities apart from IT: count me in! Though I prefer mountain biking. :heart_eyes: 

Thank you very much for your time!

**Comment by muffl0n** [comment] 2018-11-12 10:34
Nevermind, the upstream issue you linked is exactly the issue I was going to create.

**Comment by Jguer** [comment] 2018-11-12 11:46
I'm closing this since there's nothing I can do from here, this should be working out of the box and it is not. I will keep tabs on the upstream issue to see if it gets fixed.

**Closed by Jguer** 2018-11-12 11:46 UTC
Labels: upstream

**Comment by zjsxwc** [comment] 2021-03-25 06:04
hi, i had the same problem.

first i had a socks5 proxy provided by localhost port `1080`.
and i tried ` export http_proxy=socks5h://127.0.0.1:1080`,
then i ran `yay -S xxx` failed.

but i foud two way to use the socks5 proxy successfully.
one is to use `export http_proxy=socks5://127.0.0.1:1080` , here i use `socks5` instead of `socks5h`.
another one is to use `https://github.com/oyyd/http-proxy-to-socks` convert socks5 proxy to http proxy, and use http proxy.

**Comment by bcookatpcsd** [comment] 2022-01-12 20:24
Sorry for the necro bump.. 

Nothing wrong w/ yay.. it's a sudo thing.. 

https://memset.wordpress.com/2010/10/14/bash-http_proxy-from-a-user-environment-to-sudo-one/

visudo 

Default env_keep = "http_proxy https_proxy HTTP_PROXY HTTPS_PROXY"

```
[bcook@20sl-lnx ~]$ env | grep -i proxy
no_proxy=localhost,127.0.0.0/8,::1
https_proxy=http://10.20.0.69:8192/
NO_PROXY=localhost,127.0.0.0/8,::1
HTTPS_PROXY=http://10.20.0.69:8192/
HTTP_PROXY=http://10.20.0.69:8192/
http_proxy=http://10.20.0.69:8192/
[bcook@20sl-lnx ~]$ yay -Syvu 
Root      : /
Conf File : /etc/pacman.conf
DB Path   : /var/lib/pacman/
Cache Dirs: /var/cache/pacman/pkg/  
Hook Dirs : /usr/share/libalpm/hooks/  /etc/pacman.d/hooks/  
Lock File : /var/lib/pacman/db.lck
Log File  : /var/log/pacman.log
GPG Dir   : /etc/pacman.d/gnupg/
Targets   : None
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 endeavouros is up to date
 chaotic-aur is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 there is nothing to do

```

Thank you for yay..
