### ISSUE TITLE
How to disable fail fast for updates?

### ISSUE THREAD

**Issue by msrd0** [Jguer/yay#1849] opened 2022-12-08 22:25 UTC
Every now and then, an AUR package fails to compile. This is really annoying, as every time I have to manually restart the yay command to update all packages but the failing one. How can I tell yay to skip the package upgrade of the package that failed to compile, but continue with all other packages?

**Comment by grandchild** [comment] 2022-12-09 17:25
Duplicate of #848.

**Closed as completed by grandchild** 2022-12-09 17:25 UTC
Labels: Type: Bug, Status: Triage
