### ISSUE TITLE
Yay doesn't find aur packages when using --print-format

### ISSUE THREAD

**Issue by assapir** [Jguer/yay#1807] opened 2022-09-08 08:39 UTC
### Affected Version

`yay v11.3.0 - libalpm v13.0.1`

### Describe the bug

When passing `--print-format "%n %v"` to yay, it fails to find the AUR packages

### Reproduction Steps

1. Install yay from aur
2. run `yay --noconfirm --noprogressbar --needed --sync --print-format "%n %v" oh-my-zsh-git `

### Expected behavior

`oh-my-zsh-git` is installed

### Output
```sh
yay --noconfirm --noprogressbar --needed --sync --print-format "%n %v" oh-my-zsh-git raspi-config-git
error: target not found: oh-my-zsh-git
error: target not found: raspi-config-git
 -> exit status 1
```

This does work when omitting `--print-format "%n %v"` from the command line

**Comment by AladW** [comment] 2022-09-09 10:09
For repo packages --print-format can simply be passed on to pacman, for AUR packages you need to implement a custom `sprintf`-like formatter. So this is not a bug but a feature request.

**Comment by Jguer** [comment] 2022-09-10 17:28
Closing as duplicate of https://github.com/Jguer/yay/issues/1744

**Closed as completed by Jguer** 2022-09-10 17:28 UTC
Labels: Type: Bug, Status: Triage
