### ISSUE TITLE
`yay -Syu` upgrades AUR packages that have no updates

### ISSUE THREAD

**Issue by maximbaz** [Jguer/yay#24] opened 2017-05-24 17:22 UTC
I'm running code from the `dev` branch.

```
❯  yay -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
warning: sakura: local (3.4.0-2) is newer than community (3.3.4-2)
warning: zsh: ignoring package upgrade (5.2-2 => 5.3.1-2)
 there is nothing to do
:: Starting AUR upgrade...
 Checking 61/61 packages...
==> cerebro: 0.2.8-1 -> 0.2.8-1
==> dunst-git: 1.1.0.221.g1d0bfb2.826-1 -> 1.1.0.221.g1d0bfb2.826-1
==> fonts-meta-base: 1-2 -> 1-2
==> fonts-meta-extended-lt: 2-2 -> 2-2
==> jdk7: 7u79-4 -> 7u79-4
==> kubectl-bin: 1.6.3-1 -> 1.6.4-1
==> python-pygame: 1.9.3-2 -> 1.9.3-2
==> python-tqdm: 4.11.2-1 -> 4.11.2-1
==> python2-tqdm: 4.11.2-1 -> 4.11.2-1
==> slack-desktop: 2.6.0-1 -> 2.6.2-1
==> ttf-merriweather: 2.001-1 -> 2.001-1
==> ttf-merriweather-sans: 1.006-3 -> 1.006-3
==> ttf-quintessential: 1.001-3 -> 1.001-3
==> wire-desktop-beta: 2.13.2741-1 -> 2.14.2743-1
==> Proceed with upgrade? [Y/n]
```

See for example `cerebro: 0.2.8-1 -> 0.2.8-1` and similar - why does it suggest to upgrade if the versions are the same?

```
❯  yaourt -Syua
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 Foreign packages: / 61 / 61
==> Software upgrade (new version) :
aur/kubectl-bin       1.6.3-1     -> 1.6.4-1
aur/slack-desktop     2.6.0-1     -> 2.6.2-1
aur/wire-desktop-beta 2.13.2741-1 -> 2.14.2743-1
==> Continue upgrade ? [Y/n]
```

Yaourt attempts to upgrade fewer packages.

**Comment by Jguer** [comment] 2017-05-24 21:25
Duplicate of https://github.com/Jguer/yay/issues/9

I explain the reason there. Some AUR maintainers fix their non-compiling package and forget to update the `epoch` of the package as to why I prefer to compare PKGBuild modification time instead of version.
But I see this a preference that only applies to me and leaves most confused, I'll set it as default option to compare version and leave time compare as a config flag.

**Comment by maximbaz** [comment] 2017-05-24 21:28
Oops, I don't know how I could have missed myself the existing duplicate among only 10 open issues 😐 

Thanks for the explanation! I'll close it and will follow #9.

**Closed** 2017-05-24 21:28 UTC
Labels: duplicate
