### ISSUE TITLE
only works with sudo

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#1140] opened 2020-01-03 23:13 UTC
consider supporting `doas` as well (package `opendoas` in `community`)

**Comment by treeshateorcs** [comment] 2020-01-03 23:18
oof, found out about the `--sudo` config option. problem solved

**Comment by treeshateorcs** [comment] 2020-01-03 23:28
am i doing something wrong?

```
$ yay --sudo doas                                                                                                                                                                                                             invalid option 'sudo'
```

**Comment by parkerlreed** [comment] 2020-01-04 16:58
Update yay? Working on git

```
[parker@wolfcola ~]$ yay --sudo doas
[parker@wolfcola ~]$ 
```

**Comment by parkerlreed** [comment] 2020-01-04 16:59
Optionally set 

```
        "sudobin": "sudo",
```

in the config file

**Comment by treeshateorcs** [comment] 2020-01-04 17:00
```
$  yay -V
yay v9.4.2 - libalpm v12.0.1
```


i have tried setting "sudobin"

**Comment by treeshateorcs** [comment] 2020-01-04 17:14
yep. works on git, doesn't work on release

**Comment by cnt0** [comment] 2020-01-16 04:45
just noticed that yay in AUR finally got `sudobin` support. BTW you can run
```bash
yay --sudo doas --save
```
to permanently add this option to yay config.

So my question is, shouldn't sudo (and doas too) be moved to `optdepends` section in PKGBUILD? [Archwiki](https://wiki.archlinux.org/index.php/PKGBUILD#Dependencies) explicitly says:
> If the software works on multiple alternative dependencies, all of them can be listed here _[optdepends]_, instead of the depends array

**Comment by marius137** [comment] 2021-02-09 15:51
[this issue](https://github.com/Jguer/yay/issues/1194#issuecomment-612571017) has the solution

**Comment by Jguer** [comment] 2021-02-11 08:54
Closing this issue as a duplicate of #1194

**Closed by Jguer** 2021-02-11 08:54 UTC
