### ISSUE TITLE
Is it possible to display the yay search results on a single line?

### ISSUE THREAD

**Issue by mabt** [Jguer/yay#1587] opened 2021-08-19 18:24 UTC
There is an option or a tips to display the yay search results on a single line? I mean the name of the package and the description? Thanks !

**Comment by mabt** [comment] 2021-08-20 07:55
Meanwhile I found this tip :

```
yay -Ss quake3 | while read package; do read description; echo -e "$package\t$description"; done
```

**Comment by Jguer** [comment] 2021-08-21 13:11
Closing as duplicate of #1515

**Closed as completed by Jguer** 2021-08-21 13:11 UTC
Labels: Type: Feature Request, Status: Duplicate
