### ISSUE TITLE
Dependencies needed for a package update and offering a provider choice doesn't show for which package is it

### ISSUE THREAD

**Issue by Porkepix** [Jguer/yay#2185] opened 2023-05-23 07:07 UTC
### Affected Version

`yay v12.0.5.r0.g9641d2a - libalpm v13.0.2`

### Describe the bug

When updating packages requires installing packages that have multiple providers, the question is asked before any package is shown and without telling for which package is it. Especially, in the current example it's for a build dependency.

### Reproduction Steps

1. Run `yay -Syu` with a package to upgrade that requires missing dependencies with multiple providers such as rust
2. See the prompt

### Expected behavior
The question should be asked after the package list (and selection - we can skip the package requiring the choice, and therefore the choice become pointless) is done, and should tell for which package is it.

### Output

```sh
$ yay -Syu
:: Synchronizing package databases...
 core is up to date
 extra                                                                                                                                                                 8.2 MiB  8.00 MiB/s 00:01 [########################################################################################################################] 100%
 multilib is up to date
:: Searching AUR for updates...
:: Checking development packages...
:: There are 2 providers available for cargo:
:: Repository extra
    1) rust 2) rustup

Enter a number (default=1):
==>
```

**Comment by Jguer** [comment] 2023-05-23 07:21
Hey Porkepix, I'm closing as duplicate of https://github.com/Jguer/yay/issues/2073

**Closed as completed by Jguer** 2023-05-23 07:21 UTC
Labels: Type: Bug, Status: Triage
