### ISSUE TITLE
Aur package packager has invalid format

### ISSUE THREAD

**Issue by DMNerd** [Jguer/yay#1092] opened 2019-10-24 12:08 UTC
#### Affected Version
All packages and all current versions on AUR

#### Issue
When updating yay, yay itself shows:
`==> WARNING: PACKAGER should have the format 'Example Name <email@address.invalid>'`

**Comment by Jguer** [comment] 2019-10-24 15:07
Duplicate of #1085

**Closed** 2019-10-24 15:07 UTC
