### ISSUE TITLE
 yay-bin and pacman are in conflict 

### ISSUE THREAD

**Issue by Axeltherabbit** [Jguer/yay#1520] opened 2021-06-01 14:51 UTC
### Affected Version
latest `yay-bin 10.2.2-2`

### Describe the bug

there is a package conflict with libalpm.so after the update to pacman 6

### Reproduction Steps
I just can't use yay because it is looking for the old libalpm.so package, I have libalpm.so.13 

### Output
https://pastebin.com/fBsqaXvS

**Comment by KevinRouchut** [comment] 2021-06-01 14:53
Same problem here.

**Comment by dominickleppich** [comment] 2021-06-01 15:33
I can confirm this as well.

**EDIT:** This was easily solved by reinstalling:
```
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
```

**Comment by matthewarmand** [comment] 2021-06-01 15:57
`yay` itself just needs a recompile locally, see [this AUR comment](https://aur.archlinux.org/packages/yay#pinned-808720).

`yay-bin` will need a recompile and therefore a new release, see [this AUR comment](https://aur.archlinux.org/packages/yay-bin#pinned-808723):

>It will take a bit to release the yay-bin binaries compiled with pacman 6 support

I am curious as to the timeline of a new `yay-bin` release with this support if the maintainers have an idea of that

**Comment by camdenorrb** [comment] 2021-06-01 16:08
> I can confirm this as well.
> 
> **EDIT:** This was easily solved by reinstalling:
> 
> ```
> git clone https://aur.archlinux.org/yay.git
> cd yay
> makepkg -si
> ```

Unfortuantly doesn't seem that simple for me at least

```bash
camdenorrb@new-host yay ❯ makepkg -si
==> Making package: yay 10.2.2-4 (Tue 01 Jun 2021 11:02:43 AM CDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found yay-10.2.2.tar.gz
==> Validating source files with sha256sums...
    yay-10.2.2.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-10.2.2.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
go build -trimpath -mod=readonly -modcacherw -tags six -ldflags '-X "main.yayVersion=10.2.2" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
go build: when using gccgo toolchain, please pass linker flags using -gccgoflags, not -ldflags
# github.com/Jguer/yay/v10
/usr/bin/ld: $WORK/b001/_pkg1_.a(_cgo_defun.o): relocation R_X86_64_32 against `.rodata' can not be used when making a PIE object; recompile with -fPIE
collect2: error: ld returned 1 exit status
make: *** [Makefile:112: yay] Error 2
==> ERROR: A failure occurred in build().
    Aborting...```

**Comment by shuwens** [comment] 2021-06-01 17:32
> I can confirm this as well.
> 
> **EDIT:** This was easily solved by reinstalling:
> 
> ```
> git clone https://aur.archlinux.org/yay.git
> cd yay
> makepkg -si
> ```

That indeed solved my problem, this is kind of strange :(

**Comment by Jguer** [comment] 2021-06-01 21:39
- Waiting on archlinux arm to update to pacman 6 on the `arm` and `armv6h` archs (https://archlinuxarm.org/packages)

- Looking into a solution for https://github.com/Jguer/yay/runs/2722739268 . GitHub Runners are running out of memory when cross compiling yay's builder image

**Comment by bittin** [comment] 2021-06-02 03:23
>     * Waiting on archlinux arm to update to pacman 6 on the `arm` and `armv6h` archs (https://archlinuxarm.org/packages)
> 
>     * Looking into a solution for https://github.com/Jguer/yay/runs/2722739268 . GitHub Runners are running out of memory when cross compiling yay's builder image

Got the same problem now on ALARM (Arch Linux ARM) on a Raspberry Pi 4 now today (waiting for a fix)

**Comment by Magicloud** [comment] 2021-06-02 09:26
X64, rebuilt yay, as 10.2.2-4, it still requires libalpm.so.12.

**Comment by matthewarmand** [comment] 2021-06-02 14:27
>     * Waiting on archlinux arm to update to pacman 6 on the `arm` and `armv6h` archs (https://archlinuxarm.org/packages)

Looks like this is done now: https://archlinuxarm.org/packages?q=pacman

>     * Looking into a solution for https://github.com/Jguer/yay/runs/2722739268 . GitHub Runners are running out of memory when cross compiling yay's builder image

Is this possibly related to this issue @Jguer? https://github.com/docker/buildx/issues/426#issuecomment-723208580

**Comment by bittin** [comment] 2021-06-03 05:26
> > ```
> > * Waiting on archlinux arm to update to pacman 6 on the `arm` and `armv6h` archs (https://archlinuxarm.org/packages)
> > 
> > * Looking into a solution for https://github.com/Jguer/yay/runs/2722739268 . GitHub Runners are running out of memory when cross compiling yay's builder image
> > ```
> 
> Got the same problem now on ALARM (Arch Linux ARM) on a Raspberry Pi 4 now today (waiting for a fix)

Works for me now, with the new yay version  :)

**Comment by matthewarmand** [comment] 2021-06-04 18:16
With the new `yay-bin 10.2.3-2` released earlier today, my system's back to all good. Obviously running a full system update caused `yay-bin` to be temporarily removed because the old version conflicted with `pacman 6.0.0-2`, but following the [instructions on the AUR](https://aur.archlinux.org/packages/yay-bin#pinned-808723) after that update I was able to install the new version of `yay-bin` and now we're golden. Thanks Jguer!

**Comment by Jguer** [comment] 2021-06-04 20:52
Closing, `yay-bin` seems to be stable across all platforms, thanks for your patience everyone

**Closed as completed by Jguer** 2021-06-04 20:52 UTC
Labels: Type: Bug, Status: Triage
