### ISSUE TITLE
yay -T doesn't exit with the same error code as pacman

### ISSUE THREAD

**Issue by cafehaine** [Jguer/yay#987] opened 2019-07-13 08:54 UTC
#### Affected Version
`yay v9.2.1.r9.gf406866 - libalpm v11.0.3`

#### Issue
yay returns exit code 1 instead of 127, breaking makepkg

(what I mean by this is that when running `PACMAN=yay  makepkg -si`, makepkg expects 127 and errors out)

#### Steps to reproduce
`yay -T doesntexist`, should return  127, returns 1

#### Output
```bash
$[ 0 ] 10:51 dotorico_b.> pacman -T doesntexist
doesntexist
$[127] 10:51 dotorico_b.> yay -T doesntexist
doesntexist
$[ 1 ] 10:51 dotorico_b.> 
```

**Comment by Jguer** [comment] 2019-10-24 15:19
Duplicate of #652

**Closed by Jguer** 2019-10-24 15:19 UTC
