### ISSUE TITLE
Error importing GPG keys: "no user ID"

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [Jguer/yay#1643] opened 2021-11-24 00:26 UTC
### Affected Version

yay v11.0.2 - libalpm v13.0.1

### Describe the bug

When I install a package that requires a GPG key to be imported I am met with the error:
```
gpg: key <key-to-be-imported>: no user ID
```

I've started to notice this error recently.
I've experienced it both with `mingw-w64-tools` and `nginx-rtmp`.

### Reproduction Steps

1. Install package that requires a GPG key.

### Expected behavior

I expect yay to successfully install the package in question.
### Output

Full PGP error in case of `mingw-w64-tools`:
```
:: PGP keys need importing:
 -> CAF5641F74F7DFBA88AE205693BDB53CD4EBC740, required by: mingw-w64-tools
==> Import? [Y/n] y
:: Importing keys with gpg...
gpg: key 93BDB53CD4EBC740: no user ID
gpg: Total number processed: 1
 -> problem importing keys
```

yay config:
```sh
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/rein/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "yes",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}

```

**Comment by LevitatingBusinessMan** [comment] 2021-11-24 00:36
I fixed this by changing the default keyserver used by my GPG installation (to one that doesn't strip user IDs).

I'll leave it up to the maintainers to decide if this should be closed.

**Comment by Jguer** [comment] 2021-12-03 13:42
kinda duplicate of #1022 , I'm closing it as there's not much we can do about changing user's gpg keyservers

**Closed as completed by Jguer** 2021-12-03 13:42 UTC
Labels: Type: Bug, Status: Triage

**Comment by igor47** [comment] 2022-11-16 22:47
if you came here just looking for the solution (as i did) you can import the key manually by running `gpg` with the specified `--keyserver`, and then re-try your install. example:

```
:: PGP keys need importing:
 -> 5DE3E0509C47EA3CF04A42D34AEE18F83AFDEB23, required by: googlemaps
:: Import? [Y/n] y
:: Importing keys with gpg...
gpg: key 4AEE18F83AFDEB23: no user ID
gpg: Total number processed: 1
 -> problem importing keys

$ gpg --keyserver hkps://pgp.surf.nl  --recv-keys 4AEE18F83AFDEB23
gpg: key 4AEE18F83AFDEB23: 1 duplicate signature removed
gpg: key 4AEE18F83AFDEB23: public key "GitHub (web-flow commit signing) <noreply@github.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
