### ISSUE TITLE
AUR upgrades fail catastrophically and I have to restart the upgrade all over again.

### ISSUE THREAD

**Issue by yuannan** [Jguer/yay#1385] opened 2020-10-09 05:56 UTC
#### Affected Version
v10.0.4

**Describe the bug**
Currently if one AUR package fails to install it would just fail the entire upgrade. This is horrible if you have lots of AUR packages. You have to fix the one package and then start the entire upgrade again. This means all the checks etc. If you have a slow laptop like mine it's hell. I've just spent 2+ hours upgrading AUR packages by hand one by one. I've tried a binary division upgrade technique but even then that's not fool proof and just a work around that still takes manual effort.

**To Reproduce**
Upgrade lots of AUR packages in one go and have any one of them fail.

**Expected behavior**
Check one AUR package. Upgrade it, go on to the next one. Even if one fails just skips it and go on to the next one. Maybe print an error message at the end to let you know which ones have failed instead of dying catastrophically. This would also make automated stuff much easier for other users.

**Comment by Jguer** [comment] 2020-10-09 11:59
Duplicate of https://github.com/Jguer/yay/issues/848

**Closed as completed by Jguer** 2020-10-09 11:59 UTC
Labels: Type: Bug, Status: Triage
