### ISSUE TITLE
12.0.2: yay --clean doesn't work anymore

### ISSUE THREAD

**Issue by andrei-pavel** [Jguer/yay#2070] opened 2023-04-05 08:36 UTC
### Affected Version

```sh
$ yay -V
yay v12.0.2 - libalpm v13.0.2
```

### Describe the bug

`yay --clean` doesn't work anymore. It claims that clean and refresh cannot be used together, but I'm not passing `--refresh`. It's like refresh started being enabled by default.

```sh
$ yay --clean
error: invalid option: '--clean' and '--refresh' may not be used together
 -> exit status 1
```

### Reproduction Steps

1. Run `yay --clean`.
2. Observe error.

### Expected behavior

I would have expected that no error is printed, and that dependencies are removed, just as before.

### Output

```sh
$ yay --clean --debug
[DEBUG:runner] running /sbin/sudo pacman --debug -S --clean -y -u --config /etc/pacman.conf --
error: invalid option: '--clean' and '--refresh' may not be used together
 -> exit status 1
```

```sh
$ yay -Pg
{
	"aururl": "https://aur.archlinux.org",
	"aurrpcurl": "https://aur.archlinux.org/rpc?",
	"buildDir": "/home/andrei/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"version": "12.0.2",
	"requestsplitn": 150,
	"completionrefreshtime": 7,
	"maxconcurrentdownloads": 0,
	"bottomup": true,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false,
	"singlelineresults": false,
	"separatesources": true,
	"newinstallengine": true,
	"debug": false,
	"rpc": true
}
EXIT 0
```

**Comment by Jguer** [comment] 2023-04-05 08:37
closing as intended change https://github.com/Jguer/yay/releases/tag/v12.0.0

duplicate of https://github.com/Jguer/yay/issues/2049

**Closed as completed by Jguer** 2023-04-05 08:37 UTC
Labels: Type: Bug, Status: Triage

**Comment by XeroOl** [comment] 2023-04-06 01:24
if this is intended, perhaps -cc shouldn't be mentioned in the output of `yay --help`

**Comment by Jguer** [comment] 2023-04-06 16:35
the `-cc` mentioned in `yay --help` refers to the `-S` operation that was added for the lack of targets (`pacman -Scc`)
