### ISSUE TITLE
Option to rebuild package from repo (and edit it's PKGBUILD first)

### ISSUE THREAD

**Issue by FreddieChopin** [Jguer/yay#657] opened 2018-08-25 13:58 UTC
This is more of a question or feature request than an issue.

In yaourt there was an option to edit the PKGBUILD and rebuild the packages from main repo - for example `yaourt -S -b cmake` would download CMake's files, allow me to edit them, build them after that and install what was built. I was using it from time to time to downgrade specific packages when they caused some trouble or when I just needed to check the behaviour of older versions. In the example I've given CMake, as this is quite a good use case - from time to time I was checking some of my public projects against old CMake versions to see whether the build files really work with such old version of the build tool. With yaourt this was perfectly simple, but it seems that yay allows me to do that only with packages from AUR.

Would it be possible to add an equivalent of yaourt's `-b` option to yay, or maybe I'm missing something and this is already possible? I've browsed through the man and tried a few options but they seem to make no effect on repo packages (like CMake).

I know I can sort-of emulate this by using packages like cmake-git and using tags, but it would be easier with no such workarounds (;

Thanks in advance!

**Comment by FreddieChopin** [comment] 2018-08-25 17:48
> Technically you can yay -G cmake, edit the files and then makepkg

Don't get me wrong, but for that I don't need any AUR helper (;

**Comment by Morganamilo** [comment] 2018-08-25 18:25
Duplicate of #5.

**Closed** 2018-08-31 09:17 UTC
