### ISSUE TITLE
cannot upgrade zfs-dkms and zfs-utils

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#1736] opened 2022-03-28 06:01 UTC
### Affected Version

yay v11.1.2.r4.ged62496 - libalpm v13.0.1

### Describe the bug

`yay` cannot figure out how to upgrade `zfs-dkms` and `zfs-utils` because `zfs-dkms` depends on `zfs-utils`.

### Reproduction Steps

1. have an old version of `zfs-dkms` and `zfs-utils` installed
2. run `yay -Syu --devel` or `yay -Syu --devel --batchinstall`

### Expected behavior

`yay` upgrades the two packages

### Output

```
$ yay -Pg
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/nox/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"completionrefreshtime": 7,
	"bottomup": true,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false,
	"singlelineresults": false,
	"separatesources": false,
	"version": "11.1.2.r4.ged62496"
}
```
```
$ yay -Syu --devel --batchinstall
:: Checking development packages...
==> :: Checking for conflicts...
:: Checking for inner conflicts...
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
mangoduck@peridot% ~/ cat media/256GB/output | xclip -sel clip
mangoduck@peridot% ~/ cat media/256GB/output                  
:: Synchronizing package databases...
 core downloading...
 extra downloading...
 community downloading...
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
:: Checking development packages...
:: 2 Packages to upgrade.
2  aur/zfs-dkms   2.1.3-1 -> 2.1.4-1
1  aur/zfs-utils  2.1.3-1 -> 2.1.4-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> :: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:2]  zfs-utils-2.1.4-1  zfs-dkms-2.1.4-1

  2 zfs-utils                                (Installed) (Build Files Exist)
  1 zfs-dkms                                 (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> :: PKGBUILD up to date, Skipping (2/0): zfs-utils, zfs-dkms
  2 zfs-utils                                (Installed) (Build Files Exist)
  1 zfs-dkms                                 (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> :: (1/2) Parsing SRCINFO: zfs-utils
:: (2/2) Parsing SRCINFO: zfs-dkms
==> Making package: zfs-dkms 2.1.4-1 (Sun 27 Mar 2022 10:35:46 PM PDT)
==> Retrieving sources...
  -> Found zfs-2.1.4.tar.gz
  -> Found zfs-2.1.4.tar.gz.asc
  -> Found 0001-only-build-the-module-in-dkms.conf.patch
==> Validating source files with sha256sums...
==> Validating source files with b2sums...
==> Verifying source file signatures with gpg...
==> Making package: zfs-utils 2.1.4-1 (Sun 27 Mar 2022 10:35:47 PM PDT)
==> Retrieving sources...
  -> Found zfs-2.1.4.tar.gz
  -> Found zfs-2.1.4.tar.gz.asc
  -> Found zfs.initcpio.install
  -> Found zfs.initcpio.hook
==> Validating source files with sha256sums...
==> Validating source files with b2sums...
==> Verifying source file signatures with gpg...
==> Making package: zfs-utils 2.1.4-1 (Sun 27 Mar 2022 10:35:50 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found zfs-2.1.4.tar.gz
  -> Found zfs-2.1.4.tar.gz.asc
  -> Found zfs.initcpio.install
  -> Found zfs.initcpio.hook
==> Validating source files with sha256sums...
==> Validating source files with b2sums...
==> Verifying source file signatures with gpg...
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting zfs-2.1.4.tar.gz with bsdtar
==> Starting prepare()...
==> Sources are ready.
==> Making package: zfs-utils 2.1.4-1 (Sun 27 Mar 2022 10:35:56 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Sources are ready.
 -> zfs-utils-2.1.4-1 already made -- skipping build
 -> zfs-utils=2.1.4 not satisfied, flushing install queue
loading packages...
resolving dependencies...
looking for conflicting packages...
:: installing zfs-utils (2.1.4-1) breaks dependency 'zfs-utils=2.1.3' required by zfs-dkms
```

**Comment by grandchild** [comment] 2022-03-29 17:56
Duplicate of #803, #1275, #1457, possibly others.

**Comment by Jguer** [comment] 2023-02-21 01:03
Should be fixed in `yay-git`, if it's not (I think there might be an order dependent case) an extra step can be added to retry adding failed packages one more time to the graph.

Closing until more feedback

**Closed as completed by Jguer** 2023-02-21 01:03 UTC
Labels: Type: Bug, Status: Triage

**Comment by Axionize** [comment] 2024-02-26 19:38
This seem to work but only for `zfs-utils` and `zfs-dkms` with `yay -Syu` regardless if the `--batchinstall` flag is added or not. For circular dependency cases like `libnvidia-container-tools` and `nvidia-container-toolkit` yay still will not upgrade the packages.
