### ISSUE TITLE
Cannot compile yay

### ISSUE THREAD

**Issue by DawfukFR** [Jguer/yay#2394] opened 2024-03-13 14:40 UTC
### Distro
Archlinux with testing repo

### Describe the bug

../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/db_six.go:29:103: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_group_pkgs
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:26:75: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_handle_t) as *_Ctype_struct__alpm_handle_t value in argument to _Cfunc_alpm_find_dbs_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:26:75: cannot use _cgo1 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_dbs_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:43:78: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/package_six.go:42:53: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_list_count
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/package_six.go:43:34: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_list_msort

### Reproduction Steps

pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

**Comment by Trit34** [comment] 2024-03-13 14:45
Duplicate of https://github.com/Jguer/yay/issues/2393

**Comment by DawfukFR** [comment] 2024-03-13 14:52
> Duplicate of #2393

is it same as this error ?
yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory

**Closed as completed** 2024-03-13 16:02 UTC
Labels: Type: Bug, Status: Triage, Status: Duplicate

**Comment by mogwa1** [comment] 2024-03-18 13:01
Can this please be re-opened?  This is not the same as the libalpm.so.13 version mismatch.

I got this exact same error on a 32-bit armv7h system (running archlinuxarm).  The same system booted with a 64-bit OS had no problems.  So it seems that this is really coupled to 32-bit systems.
I did not have issues with 12.3.0 on the 32-bit system.  So something must have changed in between 12.3.0 and 12.3.4.

```
# github.com/Jguer/go-alpm/v2
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/db_six.go:29:103: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_group_pkgs
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:26:75: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_handle_t) as *_Ctype_struct__alpm_handle_t value in argument to _Cfunc_alpm_find_dbs_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:26:75: cannot use _cgo1 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_dbs_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:43:78: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_find_satisfier
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/package_six.go:42:53: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_list_count
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/package_six.go:43:34: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t value in argument to _Cfunc_alpm_list_msort
make: *** [Makefile:115: yay] Error 1
```

**Comment by ASmyrnyi** [comment] 2024-05-04 14:43
Got the same error on Steam Deck. The issue seems to be closed, but I don't understand what's the fix

**Comment by mlt** [comment] 2025-11-27 06:13
If you are getting this, you have incompatible libalpm installed. If you can't update, try an older version like `git checkout v12.3.4`. At least this is the case with Ubuntu 24.04…don't ask.
<details>
  <summary>Click to expand</summary>

```
mlt@DESKTOP-K26J5U0:~/yay$ git checkout v12.3.4
Previous HEAD position was 2ff794d chore: update go-alpm (#2409)
HEAD is now at a1d530c Updates for file po/en.po in hu (#2401)
mlt@DESKTOP-K26J5U0:~/yay$ make
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=12.0.0" -X "main.localePath=/usr/local/share/locale/" -linkmode=external' -buildmode=pie -o yay
go: downloading github.com/Jguer/go-alpm/v2 v2.2.1
mlt@DESKTOP-K26J5U0:~/yay$ ./yay
:: Synchronizing package databases...
 core is up to date
 extra is up to date
:: Searching AUR for updates...
:: Searching databases for updates...
 there is nothing to do
mlt@DESKTOP-K26J5U0:~/yay$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.3 LTS
Release:        24.04
Codename:       noble
```
</details>
