### ISSUE TITLE
The new output is annoying

### ISSUE THREAD

**Issue by idc77** [Jguer/yay#2095] opened 2023-04-07 11:07 UTC
### Affected Version

yay v12.0.2 - libalpm v13.0.2

### Describe the bug

the new colorized and vertically listed output is very annoying

### Reproduction Steps

1. install the new yay
2. suffer
3. hate yay

### Expected behavior

Old, now newline separated output, pacman style

### Output
new style :-1: 
```
143  core/hwdata                              0.368-1          -> 0.369-1
142  core/systemd                             253.2-2          -> 253.3-1
141  core/systemd-libs                        253.2-2          -> 253.3-1
140  core/systemd-sysvcompat                  253.2-2          -> 253.3-1
139  extra/bluedevil                          1:5.27.3-1       -> 1:5.27.4-1
138  extra/breeze                             5.27.3-1         -> 5.27.4-1
137  extra/breeze-gtk                         5.27.3-1         -> 5.27.4-1
136  extra/breeze-plymouth                    5.27.3-1         -> 5.27.4-1
135  extra/cmake                              3.26.2-1         -> 3.26.3-1
134  extra/discover                           5.27.3-1         -> 5.27.4-1
133  extra/drkonqi                            5.27.3-1         -> 5.27.4-1
132  extra/flatpak-kcm                        5.27.3-1         -> 5.27.4-1
131  extra/kactivitymanagerd                  5.27.3-1         -> 5.27.4-1
130  extra/kde-cli-tools                      5.27.3-1         -> 5.27.4-1
129  extra/kde-gtk-config                     5.27.3-1         -> 5.27.4-1
128  extra/kdecoration                        5.27.3-1         -> 5.27.4-1
127  extra/kdeplasma-addons                   5.27.3-1         -> 5.27.4-1
126  extra/kgamma5                            5.27.3-1         -> 5.27.4-1
125  extra/khotkeys                           5.27.3-1         -> 5.27.4-1
124  extra/kinfocenter                        5.27.3-1         -> 5.27.4-1
123  extra/kmenuedit                          5.27.3-1         -> 5.27.4-1
122  extra/kpipewire                          5.27.3-1         -> 5.27.4-1
121  extra/kscreen                            5.27.3-1         -> 5.27.4-1
120  extra/kscreenlocker                      5.27.3-1         -> 5.27.4-1
119  extra/ksshaskpass                        5.27.3-1         -> 5.27.4-1
118  extra/ksystemstats                       5.27.3-1         -> 5.27.4-1
117  extra/kwallet-pam                        5.27.3-1         -> 5.27.4-1
116  extra/kwayland-integration               5.27.3-1         -> 5.27.4-1
115  extra/kwin                               5.27.3-2         -> 5.27.4-1
114  extra/kwrited                            5.27.3-1         -> 5.27.4-1
113  extra/layer-shell-qt                     5.27.3-1         -> 5.27.4-1
112  extra/libkscreen                         5.27.3-1         -> 5.27.4-1
111  extra/libksysguard                       5.27.3-1         -> 5.27.4-1
110  extra/milou                              5.27.3-1         -> 5.27.4-1
109  extra/oxygen                             5.27.3-1         -> 5.27.4-1
108  extra/oxygen-sounds                      5.27.3-1         -> 5.27.4-1
107  extra/plasma-browser-integration         5.27.3-1         -> 5.27.4-1
106  extra/plasma-desktop                     5.27.3-1         -> 5.27.4-1
105  extra/plasma-disks                       5.27.3-1         -> 5.27.4-1
104  extra/plasma-firewall                    5.27.3-1         -> 5.27.4-1
103  extra/plasma-integration                 5.27.3-2         -> 5.27.4-1
102  extra/plasma-nm                          5.27.3-1         -> 5.27.4-1
101  extra/plasma-pa                          5.27.3-1         -> 5.27.4-1
100  extra/plasma-sdk                         5.27.3-1         -> 5.27.4-1
 99  extra/plasma-systemmonitor               5.27.3-1         -> 5.27.4-1
 98  extra/plasma-thunderbolt                 5.27.3-1         -> 5.27.4-1
 97  extra/plasma-vault                       5.27.3-1         -> 5.27.4.1-1
 96  extra/plasma-wayland-session             5.27.3-1         -> 5.27.4.1-1
 95  extra/plasma-welcome                     5.27.3-1         -> 5.27.4.1-1
 94  extra/plasma-workspace                   5.27.3-1         -> 5.27.4.1-1
 93  extra/plasma-workspace-wallpapers        5.27.3-1         -> 5.27.4.1-1
 92  extra/plymouth-kcm                       5.27.3-3         -> 5.27.4.1-1
 91  extra/polkit-kde-agent                   5.27.3-1         -> 5.27.4.1-1
 90  extra/powerdevil                         5.27.3-1         -> 5.27.4.1-1
 89  extra/python-cryptography                39.0.2-1         -> 40.0.1-1
 88  extra/qemu-audio-alsa                    7.2.0-5          -> 7.2.1-1
 87  extra/qemu-audio-dbus                    7.2.0-5          -> 7.2.1-1
 86  extra/qemu-audio-jack                    7.2.0-5          -> 7.2.1-1
 85  extra/qemu-audio-oss                     7.2.0-5          -> 7.2.1-1
 84  extra/qemu-audio-pa                      7.2.0-5          -> 7.2.1-1
 83  extra/qemu-audio-sdl                     7.2.0-5          -> 7.2.1-1
 82  extra/qemu-audio-spice                   7.2.0-5          -> 7.2.1-1
 81  extra/qemu-block-curl                    7.2.0-5          -> 7.2.1-1
 80  extra/qemu-block-dmg                     7.2.0-5          -> 7.2.1-1
 79  extra/qemu-block-nfs                     7.2.0-5          -> 7.2.1-1
 78  extra/qemu-block-ssh                     7.2.0-5          -> 7.2.1-1
 77  extra/qemu-chardev-spice                 7.2.0-5          -> 7.2.1-1
 76  extra/qemu-common                        7.2.0-5          -> 7.2.1-1
 75  extra/qemu-desktop                       7.2.0-5          -> 7.2.1-1
 74  extra/qemu-emulators-full                7.2.0-5          -> 7.2.1-1
 73  extra/qemu-hw-display-qxl                7.2.0-5          -> 7.2.1-1
 72  extra/qemu-hw-display-virtio-gpu         7.2.0-5          -> 7.2.1-1
 71  extra/qemu-hw-display-virtio-gpu-gl      7.2.0-5          -> 7.2.1-1
 70  extra/qemu-hw-display-virtio-gpu-pci     7.2.0-5          -> 7.2.1-1
 69  extra/qemu-hw-display-virtio-gpu-pci-gl  7.2.0-5          -> 7.2.1-1
 68  extra/qemu-hw-display-virtio-vga         7.2.0-5          -> 7.2.1-1
 67  extra/qemu-hw-display-virtio-vga-gl      7.2.0-5          -> 7.2.1-1
 66  extra/qemu-hw-s390x-virtio-gpu-ccw       7.2.0-5          -> 7.2.1-1
 65  extra/qemu-hw-usb-host                   7.2.0-5          -> 7.2.1-1
 64  extra/qemu-hw-usb-redirect               7.2.0-5          -> 7.2.1-1
 63  extra/qemu-hw-usb-smartcard              7.2.0-5          -> 7.2.1-1
 62  extra/qemu-img                           7.2.0-5          -> 7.2.1-1
 61  extra/qemu-pr-helper                     7.2.0-5          -> 7.2.1-1
 60  extra/qemu-system-aarch64                7.2.0-5          -> 7.2.1-1
 59  extra/qemu-system-alpha                  7.2.0-5          -> 7.2.1-1
 58  extra/qemu-system-alpha-firmware         7.2.0-5          -> 7.2.1-1
 57  extra/qemu-system-arm                    7.2.0-5          -> 7.2.1-1
 56  extra/qemu-system-arm-firmware           7.2.0-5          -> 7.2.1-1
 55  extra/qemu-system-avr                    7.2.0-5          -> 7.2.1-1
 54  extra/qemu-system-cris                   7.2.0-5          -> 7.2.1-1
 53  extra/qemu-system-hppa                   7.2.0-5          -> 7.2.1-1
 52  extra/qemu-system-hppa-firmware          7.2.0-5          -> 7.2.1-1
 51  extra/qemu-system-loongarch64            7.2.0-5          -> 7.2.1-1
 50  extra/qemu-system-m68k                   7.2.0-5          -> 7.2.1-1
 49  extra/qemu-system-microblaze             7.2.0-5          -> 7.2.1-1
 48  extra/qemu-system-microblaze-firmware    7.2.0-5          -> 7.2.1-1
 47  extra/qemu-system-mips                   7.2.0-5          -> 7.2.1-1
 46  extra/qemu-system-nios2                  7.2.0-5          -> 7.2.1-1
 45  extra/qemu-system-or1k                   7.2.0-5          -> 7.2.1-1
 44  extra/qemu-system-ppc                    7.2.0-5          -> 7.2.1-1
 43  extra/qemu-system-ppc-firmware           7.2.0-5          -> 7.2.1-1
 42  extra/qemu-system-riscv                  7.2.0-5          -> 7.2.1-1
 41  extra/qemu-system-riscv-firmware         7.2.0-5          -> 7.2.1-1
 40  extra/qemu-system-rx                     7.2.0-5          -> 7.2.1-1
 39  extra/qemu-system-s390x                  7.2.0-5          -> 7.2.1-1
 38  extra/qemu-system-s390x-firmware         7.2.0-5          -> 7.2.1-1
 37  extra/qemu-system-sh4                    7.2.0-5          -> 7.2.1-1
 36  extra/qemu-system-sparc                  7.2.0-5          -> 7.2.1-1
 35  extra/qemu-system-sparc-firmware         7.2.0-5          -> 7.2.1-1
 34  extra/qemu-system-tricore                7.2.0-5          -> 7.2.1-1
 33  extra/qemu-system-x86                    7.2.0-5          -> 7.2.1-1
 32  extra/qemu-system-x86-firmware           7.2.0-5          -> 7.2.1-1
 31  extra/qemu-system-xtensa                 7.2.0-5          -> 7.2.1-1
 30  extra/qemu-tools                         7.2.0-5          -> 7.2.1-1
 29  extra/qemu-ui-curses                     7.2.0-5          -> 7.2.1-1
 28  extra/qemu-ui-dbus                       7.2.0-5          -> 7.2.1-1
 27  extra/qemu-ui-egl-headless               7.2.0-5          -> 7.2.1-1
 26  extra/qemu-ui-gtk                        7.2.0-5          -> 7.2.1-1
 25  extra/qemu-ui-opengl                     7.2.0-5          -> 7.2.1-1
 24  extra/qemu-ui-sdl                        7.2.0-5          -> 7.2.1-1
 23  extra/qemu-ui-spice-app                  7.2.0-5          -> 7.2.1-1
 22  extra/qemu-ui-spice-core                 7.2.0-5          -> 7.2.1-1
 21  extra/qemu-user                          7.2.0-5          -> 7.2.1-1
 20  extra/qemu-vhost-user-gpu                7.2.0-5          -> 7.2.1-1
 19  extra/qemu-virtiofsd                     7.2.0-5          -> 7.2.1-1
 18  extra/sddm-kcm                           5.27.3-1         -> 5.27.4.1-1
 17  extra/systemsettings                     5.27.3-1         -> 5.27.4.1-1
 16  extra/wayland                            1.21.0-2         -> 1.22.0-1
 15  extra/xdg-desktop-portal-kde             5.27.3-1         -> 5.27.4.1-1
 14  community/go                             2:1.20.2-1       -> 2:1.20.3-1
 13  community/opera                          97.0.4719.43-1   -> 97.0.4719.63-1
 12  community/opera-ffmpeg-codecs            111.0.5563.111-1 -> 111.0.5563.147-1
 11  community/percona-toolkit                3.5.1-1          -> 3.5.2-1
 10  community/python-docutils                1:0.19-2         -> 1:0.19-3
  9  community/python-jaraco.itertools        6.2.1-2          -> 6.2.1-3
  8  community/python-jaraco.stream           3.0.3-2          -> 3.0.3-3
  7  community/python-pyzmq                   24.0.1-2         -> 25.0.2-1
  6  community/python-tomlkit                 0.11.6-1         -> 0.11.7-1
  5  community/rubberband                     3.1.2-1          -> 3.2.1-1
  4  multilib/lib32-systemd                   253.2-1          -> 253.3-1
  3  aur/visual-studio-code-bin               1.77.0-1         -> 1.77.1-1
  2  aur/vscodium-bin                         1.77.0.23093-1   -> 1.77.1.23095-1
  1  aur/yay                                  12.0.2-1         -> 12.0.3-1
```
old pacman style :+1: 
```
Packages (140) bluedevil-1:5.27.4-1  breeze-5.27.4-1  breeze-gtk-5.27.4-1  breeze-plymouth-5.27.4-1  cmake-3.26.3-1
               discover-5.27.4-1  drkonqi-5.27.4-1  flatpak-kcm-5.27.4-1  go-2:1.20.3-1  hwdata-0.369-1  kactivitymanagerd-5.27.4-1
               kde-cli-tools-5.27.4-1  kde-gtk-config-5.27.4-1  kdecoration-5.27.4-1  kdeplasma-addons-5.27.4-1  kgamma5-5.27.4-1
               khotkeys-5.27.4-1  kinfocenter-5.27.4-1  kmenuedit-5.27.4-1  kpipewire-5.27.4-1  kscreen-5.27.4-1
               kscreenlocker-5.27.4-1  ksshaskpass-5.27.4-1  ksystemstats-5.27.4-1  kwallet-pam-5.27.4-1
               kwayland-integration-5.27.4-1  kwin-5.27.4-1  kwrited-5.27.4-1  layer-shell-qt-5.27.4-1  lib32-systemd-253.3-1
               libkscreen-5.27.4-1  libksysguard-5.27.4-1  milou-5.27.4-1  opera-97.0.4719.63-1
               opera-ffmpeg-codecs-111.0.5563.147-1  oxygen-5.27.4-1  oxygen-sounds-5.27.4-1  percona-toolkit-3.5.2-1
               plasma-browser-integration-5.27.4-1  plasma-desktop-5.27.4-1  plasma-disks-5.27.4-1  plasma-firewall-5.27.4-1
               plasma-integration-5.27.4-1  plasma-nm-5.27.4-1  plasma-pa-5.27.4-1  plasma-sdk-5.27.4-1
               plasma-systemmonitor-5.27.4-1  plasma-thunderbolt-5.27.4-1  plasma-vault-5.27.4.1-1
               plasma-wayland-session-5.27.4.1-1  plasma-welcome-5.27.4.1-1  plasma-workspace-5.27.4.1-1
               plasma-workspace-wallpapers-5.27.4.1-1  plymouth-kcm-5.27.4.1-1  polkit-kde-agent-5.27.4.1-1  powerdevil-5.27.4.1-1
               python-cryptography-40.0.1-1  python-docutils-1:0.19-3  python-jaraco.itertools-6.2.1-3
               python-jaraco.stream-3.0.3-3  python-pyzmq-25.0.2-1  python-tomlkit-0.11.7-1  qemu-audio-alsa-7.2.1-1
               qemu-audio-dbus-7.2.1-1  qemu-audio-jack-7.2.1-1  qemu-audio-oss-7.2.1-1  qemu-audio-pa-7.2.1-1
               qemu-audio-sdl-7.2.1-1  qemu-audio-spice-7.2.1-1  qemu-block-curl-7.2.1-1  qemu-block-dmg-7.2.1-1
               qemu-block-nfs-7.2.1-1  qemu-block-ssh-7.2.1-1  qemu-chardev-spice-7.2.1-1  qemu-common-7.2.1-1
               qemu-desktop-7.2.1-1  qemu-emulators-full-7.2.1-1  qemu-hw-display-qxl-7.2.1-1  qemu-hw-display-virtio-gpu-7.2.1-1
               qemu-hw-display-virtio-gpu-gl-7.2.1-1  qemu-hw-display-virtio-gpu-pci-7.2.1-1
               qemu-hw-display-virtio-gpu-pci-gl-7.2.1-1  qemu-hw-display-virtio-vga-7.2.1-1  qemu-hw-display-virtio-vga-gl-7.2.1-1
               qemu-hw-s390x-virtio-gpu-ccw-7.2.1-1  qemu-hw-usb-host-7.2.1-1  qemu-hw-usb-redirect-7.2.1-1
               qemu-hw-usb-smartcard-7.2.1-1  qemu-img-7.2.1-1  qemu-pr-helper-7.2.1-1  qemu-system-aarch64-7.2.1-1
               qemu-system-alpha-7.2.1-1  qemu-system-alpha-firmware-7.2.1-1  qemu-system-arm-7.2.1-1
               qemu-system-arm-firmware-7.2.1-1  qemu-system-avr-7.2.1-1  qemu-system-cris-7.2.1-1  qemu-system-hppa-7.2.1-1
               qemu-system-hppa-firmware-7.2.1-1  qemu-system-loongarch64-7.2.1-1  qemu-system-m68k-7.2.1-1
               qemu-system-microblaze-7.2.1-1  qemu-system-microblaze-firmware-7.2.1-1  qemu-system-mips-7.2.1-1
               qemu-system-nios2-7.2.1-1  qemu-system-or1k-7.2.1-1  qemu-system-ppc-7.2.1-1  qemu-system-ppc-firmware-7.2.1-1
               qemu-system-riscv-7.2.1-1  qemu-system-riscv-firmware-7.2.1-1  qemu-system-rx-7.2.1-1  qemu-system-s390x-7.2.1-1
               qemu-system-s390x-firmware-7.2.1-1  qemu-system-sh4-7.2.1-1  qemu-system-sparc-7.2.1-1
               qemu-system-sparc-firmware-7.2.1-1  qemu-system-tricore-7.2.1-1  qemu-system-x86-7.2.1-1
               qemu-system-x86-firmware-7.2.1-1  qemu-system-xtensa-7.2.1-1  qemu-tools-7.2.1-1  qemu-ui-curses-7.2.1-1
               qemu-ui-dbus-7.2.1-1  qemu-ui-egl-headless-7.2.1-1  qemu-ui-gtk-7.2.1-1  qemu-ui-opengl-7.2.1-1  qemu-ui-sdl-7.2.1-1
               qemu-ui-spice-app-7.2.1-1  qemu-ui-spice-core-7.2.1-1  qemu-user-7.2.1-1  qemu-vhost-user-gpu-7.2.1-1
               qemu-virtiofsd-7.2.1-1  rubberband-3.2.1-1  sddm-kcm-5.27.4.1-1  systemd-253.3-1  systemd-libs-253.3-1
               systemd-sysvcompat-253.3-1  systemsettings-5.27.4.1-1  wayland-1.22.0-1  xdg-desktop-portal-kde-5.27.4.1-1

Total Download Size:    500.80 MiB
Total Installed Size:  1586.56 MiB
Net Upgrade Size:        -4.73 MiB
```

**Comment by Jguer** [comment] 2023-04-07 14:57
Closing as duplicate of https://github.com/Jguer/yay/issues/2078

**Closed as completed by Jguer** 2023-04-07 14:57 UTC
Labels: Type: Bug, Status: Triage

**Comment by idc77** [comment] 2023-04-10 11:28
It is not a duplicate of #2078 . It's a completely different topic.
You added this annoying output type without an option to remove it again @Jguer

**Comment by darkbasic** [comment] 2023-04-14 13:49
Take your time to actually read the linked issue and you will find out that it indeed is a duplicate.
