### ISSUE TITLE
--cleanafter should not run after a failed install

### ISSUE THREAD

**Issue by ricochet1k** [Jguer/yay#1315] opened 2020-06-26 15:44 UTC
#### Affected Version

`yay v10.0.1 - libalpm v12.0.1`

#### Issue

After waiting for a long build, the install failed due to a conflict and `yay --cleanafter` then deleted the package files. Maybe `--cleanafter` could keep the latest package file around, or copy directly to the pacman cache so paccache can deal with it?

#### Steps to reproduce

1. yay -S sagemath-jupyter
2. yay -S sagemath-jupyter-git --cleanafter

#### Output

```
...
==> Leaving fakeroot environment.
==> Finished making: sagemath-git 9.2.beta1.r0.ge2dcdeeabb-1 (Fri 26 Jun 2020 11:31:35 AM EDT)
==> Cleaning up...
 -> Found git repo: git.sagemath.org/sage.git
[sudo] password for matt: 
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) sagemath-jupyter-git-9.2.beta1.r0.ge2dcdeeabb-1

Total Installed Size:  0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                                                                      [#####################################################################################################] 100%
(1/1) checking package integrity                                                                                                                                    [#####################################################################################################] 100%
(1/1) loading package files                                                                                                                                         [#####################################################################################################] 100%
(1/1) checking for file conflicts                                                                                                                                   [#####################################################################################################] 100%
error: failed to commit transaction (conflicting files)
sagemath-jupyter-git: /usr/share/jupyter/kernels/sagemath/doc exists in filesystem (owned by sagemath-jupyter)
sagemath-jupyter-git: /usr/share/jupyter/kernels/sagemath/kernel.json exists in filesystem (owned by sagemath-jupyter)
sagemath-jupyter-git: /usr/share/jupyter/kernels/sagemath/logo-64x64.png exists in filesystem (owned by sagemath-jupyter)
sagemath-jupyter-git: /usr/share/jupyter/kernels/sagemath/logo.svg exists in filesystem (owned by sagemath-jupyter)
sagemath-jupyter-git: /usr/share/jupyter/nbextensions/jsmol exists in filesystem (owned by sagemath-jupyter)
sagemath-jupyter-git: /usr/share/jupyter/nbextensions/mathjax exists in filesystem (owned by sagemath-jupyter)
sagemath-jupyter-git: /usr/share/jupyter/nbextensions/threejs exists in filesystem (owned by sagemath-jupyter)
Errors occurred, no packages were upgraded.
removing untracked AUR files from cache...
:: Cleaning (1/1): /home/matt/.cache/yay/sagemath-git
Removing sagemath-git-9.2.beta1.r0.ge2dcdeeabb-1-x86_64.pkg.tar.xz
Removing sagemath-jupyter-git-9.2.beta1.r0.ge2dcdeeabb-1-x86_64.pkg.tar.xz
```

```
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/matt/.cache/yay",
	"absdir": "/home/matt/.cache/yay/abs",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": true,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}
```

**Comment by grandchild** [comment] 2020-06-30 13:24
There's an argument to be made, that `--cleanafter` does exactly what it says. Maybe one could have a `--cleanaftersuccess` flag or something similar for this usecase?

**Comment by ricochet1k** [comment] 2020-06-30 15:15
```
    --cleanafter          Remove package sources after successful install
```
Two problems I see: It isn't removing just the package sources, it is removing the package final product, and it wasn't a successful install. So no, it *not* doing exactly what it says.

**Comment by Jguer** [comment] 2020-07-01 06:59
Ok so I see this issue breaks down into two:

- ` --cleanafter removes package sources and final product`
Yes, since we changed to using `git clean` for cleanafter this is what happens, we should add a `-exclude=*.pkg.*` to it to fix the first issue.  

- `--cleanafter should not run after a failed install `
Is a bug and should be fixed

Thanks for the feedback @ricochet1k (@grandchild also thank you because lately you've been killing it on support tickets)

**Comment by Jguer** [comment] 2020-07-01 07:21
` --cleanafter removes package sources and final product` is fixed on  https://github.com/Jguer/yay/commit/b5b4484c5c68124d996e547e3250e61d822a6062 and in `yay-git`.

The other issue will require some heavy refactoring so it has to be thought out before

**Comment by Raymo111** [comment] 2021-10-15 16:40
@Jguer any update on this? `--cleanafter` is still removing package sources after a failed install which is causing me to have to redownload massive packages :cry:

**Comment by vmw** [comment] 2021-11-05 14:09
Hi,

This also happened to me. Again, this occurred after a fairly long build, and the installation failed because files already existed in the system.

PROBLEM

It looks like yay doesn't save compiled packages if they aren't installed successfully.

REPRODUCTION

This occurred when attempting to install something using binary packages - the PKGBUILD in question does not use git. 

0) Create an empty file in a location that would otherwise be used by that package.
1) Run yay -S <package name>
2) You'll get the following error during installation;

```
[...]
(1/1) loading package files                                                                                                                   [#######################################################################################] 100%
(1/1) checking for file conflicts                                                                                                             [#######################################################################################] 100%
error: failed to commit transaction (conflicting files)
package: /etc/package/config.conf exists in filesystem
```
EXPECTED

That the package still exists, somewhere, ready for re-installation once the issues are fixed.

ACTUAL

The package is gone. :(

VERSIONS

$ yay --version
yay v11.0.2.r21.g53e8ec7 - libalpm v13.0.1

I've installed the yay-git version on Archlinux (ie; https://aur.archlinux.org/packages/yay-git/ ), with the default makepkg (available here; https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yay-git ), which seems to pull from your next branch.

**Comment by haselwarter** [comment] 2022-08-18 09:40
Bump. This bug essentially renders `--cleanafter` useless: in combination with `--batchinstall` it regularly results in losing very time intensive builds.

**Comment by xeruf** [comment] 2022-09-25 15:18
I have to concur.
The commit mentioned above (https://github.com/Jguer/yay/commit/b5b4484c5c68124d996e547e3250e61d822a6062) does not seem to be in effect anymore, built pkgs are removed, and the description also changed:
```sh
       --cleanafter
              Remove untracked files after installation.

              Untracked files are removed with the exception of directories.  This allows VCS packages to
              easily pull an update instead of having to reclone the entire repo.

       --nocleanafter
              Do not remove package sources after successful Install.
```

**Comment by Jguer** [comment] 2023-02-21 02:10
There was an issue with quoting that has been fixed, this should now work as expected

**Closed by Jguer** 2023-02-21 02:10 UTC
Labels: Type: Bug, help wanted, Status: Confirmed
