### ISSUE TITLE
Build failure on ARM

### ISSUE THREAD

**Issue by drws** [Jguer/yay#2402] opened 2024-03-18 15:18 UTC
### Affected Version

Should be _yay v12.3.4 - libalpm v14.0.0_, but the issue occurs already during build.

### Describe the bug

The `build()` function is recently failing on Arch ARM with:

```
# runtime/cgo
gcc: error: unrecognized command-line option '-mno-omit-leaf-frame-pointer'; did you mean '-fno-omit-frame-pointer'?
```

### Reproduction Steps

1. `makepkg`
2. The error is printed during `build()`.

### Expected behavior

No error, as in previous Yay versions (before the Pacman v6.1.0 and ALPM v 14.0 update).

### Output

**Comment by CountMurphy** [comment] 2024-03-18 15:28
Same error on my end.

**Comment by Jguer** [comment] 2024-03-18 16:08
hey @drws , can you check your makepkg.conf? It might be a new option that was added to your CFLAGS

**Comment by CountMurphy** [comment] 2024-03-18 16:27
That removed that error for me, but now it failing a clean build with: 

```
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/db_six.go:29:103: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t
 value in argument to _Cfunc_alpm_find_group_pkgs                                                                                                                      
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:26:75: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_handle_t) as *_Ctype_struct__alpm_handle_
t value in argument to _Cfunc_alpm_find_dbs_satisfier                                                                                                                  
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:26:75: cannot use _cgo1 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t va
lue in argument to _Cfunc_alpm_find_dbs_satisfier                                                                                                                      
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/deps.go:43:78: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_list_t va
lue in argument to _Cfunc_alpm_find_satisfier                                                                                                                          
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/package_six.go:42:53: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_li
st_t value in argument to _Cfunc_alpm_list_count                                                                                                                       
../gopath/pkg/mod/github.com/!jguer/go-alpm/v2@v2.2.1/package_six.go:43:34: cannot use _cgo0 (variable of type *_Ctype_struct___alpm_list_t) as *_Ctype_struct__alpm_li
st_t value in argument to _Cfunc_alpm_list_msort                                                                                                                       
make: *** [Makefile:115: yay] Error 1     
```

**Comment by moabeat-berlin** [comment] 2024-03-19 19:29
Actually this is not a problem in yay, but rather in the go bindings for libalpm in the other Github repo. The issue is, that there are three underscores after "struct" in the pointer type, while the functions are expecting pointers with only two underscores. If you change the pointer types for the variables to two underscores, it compiles just fine. Since this doesn't seem to be a problem on x86_64 (my update went fine), the question is: Why is this only an issue on ARM architecture?

**Comment by sabrsorensen** [comment] 2024-03-19 22:08
Additional data point: aarch64/ARM64 is able to compile successfully, it seems to be limited to armv7l where I've encountered the issue.

**Comment by moabeat-berlin** [comment] 2024-03-20 23:35
I think the issue was introduced in [this commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=yay&id=1aeb6401d87131a7790a739fdbd2a53751f32821) on the AUR PKGBUILD. For a reason not apparent to me the environment variable `GOFLAGS` is expanded with `-tags=next` only if libalpm in version 14 is installed for 64 bit architectures.

If the condition for this expansion is changes from `pacman -T 'libalpm.so=14-64'` to `pacman -T 'libalpm.so=14'` the package also builds just fine on both armhf/ARM32 and on x86_64. I have no aarch64/ARM64 here to test, but I would assume it's also just fine.

So anyone can temporary fix that issue by manually patching the PKGBUILD for yay for now.

**Comment by tonivade** [comment] 2024-03-21 10:04
> If the condition for this expansion is changes from `pacman -T 'libalpm.so=14-64'` to `pacman -T 'libalpm.so=14'` the package also builds just fine on both armhf/ARM32 and on x86_64. I have no aarch64/ARM64 here to test, but I would assume it's also just fine.

I can confirm the fix worked in both armhf (rpi2) and aarch64 (rpi5)

**Comment by tomasmez** [comment] 2024-03-21 11:40
Hello,

tried building with the proposed fix on armv7l but it fails the same way using the following change:
```
build() {
  export GOPATH="$srcdir"/gopath
  export CGO_CPPFLAGS="${CPPFLAGS}"
  export CGO_CFLAGS="${CFLAGS}"
  export CGO_CXXFLAGS="${CXXFLAGS}"
  export CGO_LDFLAGS="${LDFLAGS}"
  export GOFLAGS="${GOFLAGS} $(pacman -T 'libalpm.so=14' > /dev/null && echo "-tags=next")"
  export CGO_ENABLED=1

  cd "$srcdir/$pkgname-$pkgver"
  make VERSION=$pkgver DESTDIR="$pkgdir" PREFIX="/usr" build
}

```

```
==> Starting build()...
go build -trimpath -mod=readonly -modcacherw  -ldflags '-X "main.yayVersion=12.3.4" -X "main.localePath=/usr/share/locale/" -linkmode=external' -buildmode=pie -o yay
# runtime/cgo
gcc: error: unrecognized command-line option '-mno-omit-leaf-frame-pointer'; did you mean '-fno-omit-frame-pointer'?
make: *** [Makefile:115: yay] Error 1
==> ERROR: A failure occurred in build().
    Aborting...

```

editing the -mno-omit-leaf-frame-pointer flag out of makepkg.conf fails same in https://github.com/Jguer/yay/issues/2402#issuecomment-2004382830

building latest yay against previous pacman works.
building latest yay against new pacman keeping the old makepkg.conf from 6.0.1-9 works too.

I hope this info helps find the problem.

**Comment by Jguer** [comment] 2024-03-23 18:57
:+1: I see the issue with `libalpm.so=14-64' , it will be fixed.

The `-mno-omit-leaf-frame-pointer` seems to be an issue with the cgo compiler

**Closed as completed** 2024-03-23 22:43 UTC
Labels: Type: Bug, Status: Resolved
