### ISSUE TITLE
yay -G downloads an old version of the PKGFILE

### ISSUE THREAD

**Issue by AdrienLemaire** [Jguer/yay#1146] opened 2020-01-10 00:41 UTC
#### Affected Version

```console
$ yay -V
yay v9.4.2 - libalpm v12.0.1
```

#### Issue

I'd like to rebuild the bemenu package using the cmake flag `-DBEMENU_WAYLAND_RENDERER=ON`, so I performed a `yay -G` to retrieve the PKGFILE from ABS, to realize that the PKGFILE is outdated (v0.1.0 vs current package v0.3.0-1)

#### Steps to reproduce

```console
$ yay -G bemenu
$ grep pkgver= bemenu/PKGBUILD
pkgver=0.1.0
$ pacman -Ss bemenu
community/bemenu 0.3.0-1 [installed]
    Dynamic menu library and client program inspired by dmenu with support for wayland compositors
$ yay -Ss bemenu
aur/bemenu-dmenu 1-1 (+2 0.01%)
    Symlink for using bemenu as a drop-in replacement to dmenu
aur/bemenu-git r280.121367b-1 (+15 0.11%)
    Dynamic menu library and client program inspired by dmenu with support for wayland compositors.
community/bemenu 0.3.0-1 (42.9 KiB 146.7 KiB) (Installed)
    Dynamic menu library and client program inspired by dmenu with support for wayland compositors
```

#### Output

<details><summary>yay -Pg</summary>

```json
{
        "aururl": "https://aur.archlinux.org",
        "buildDir": "/home/dori/.cache/yay",
        "absdir": "/home/dori/.cache/yay/abs",
        "editor": "",
        "editorflags": "",
        "makepkgbin": "makepkg",
        "makepkgconf": "",
        "pacmanbin": "pacman",
        "pacmanconf": "/etc/pacman.conf",
        "tarbin": "bsdtar",
        "redownload": "no",
        "rebuild": "no",
        "batchinstall": false,
        "answerclean": "",
        "answerdiff": "",
        "answeredit": "all",
        "answerupgrade": "",
        "gitbin": "git",
        "gpgbin": "gpg",
        "gpgflags": "",
        "mflags": "",
        "sortby": "votes",
        "searchby": "name-desc",
        "gitflags": "",
        "removemake": "ask",
        "requestsplitn": 150,
        "sortmode": 0,
        "completionrefreshtime": 7,
        "sudoloop": true,
        "timeupdate": false,
        "devel": false,
        "cleanAfter": false,
        "gitclone": true,
        "provides": true,
        "pgpfetch": true,
        "upgrademenu": true,
        "cleanmenu": true,
        "diffmenu": false,
        "editmenu": true,
        "combinedupgrade": false,
        "useask": false
}
```

</details>

**Comment by Jguer** [comment] 2020-01-12 13:39
Duplicate of #1135, I'll make a release today fixing this.

**Closed by Jguer** 2020-01-12 13:39 UTC
