### ISSUE TITLE
yay -c failed

### ISSUE THREAD

**Issue by Kayzwer** [Jguer/yay#2069] opened 2023-04-05 05:00 UTC
### Affected Version

yay v12.0.2 - libalpm v13.0.2

### Describe the bug

yay -c failed

### Reproduction Steps

just run "yay -c"

### Expected behavior

[~]$ yay -c
and list out all useless dependencies

### Output

```sh
error: invalid option: '--clean' and '--refresh' may not be used together
 -> exit status 1
```

**Comment by 0xarch** [comment] 2023-04-05 08:10
Try using ```yay -Yc``` instead of ```yay -c``` \(mentioned in  [Release 12.0](https://github.com/Jguer/yay/releases/tag/v12.0.0)\)

**Comment by Jguer** [comment] 2023-04-05 08:18
closing as intended change https://github.com/Jguer/yay/releases/tag/v12.0.0 

duplicate of https://github.com/Jguer/yay/issues/2049

**Closed as completed by Jguer** 2023-04-05 08:18 UTC
Labels: Type: Bug, Status: Triage
