### ISSUE TITLE
yay 10.1.0

### ISSUE THREAD

**Issue by ghost** [Jguer/yay#1396] opened 2020-10-24 13:17 UTC
This version is very slow probably due to bugs

**Comment by marek-lach** [comment] 2020-10-24 14:18
> This version is very slow probably due to bugs

You mean #1390

**Comment by Jguer** [comment] 2020-10-25 20:15
Closing as duplicate of #1390 there is indeed a performance regression which will be fixed by yay 10.1.1

**Closed as completed by Jguer** 2020-10-25 20:16 UTC
