### ISSUE TITLE
cannot install emacs26-git: Could not find PKGDEST for: emacs-git

### ISSUE THREAD

**Issue by zhou13** [Jguer/yay#590] opened 2018-07-26 19:03 UTC
#### Affected Version
yay v8.922

#### Steps to reproduce
1. `yay --edit-menu -S emacs-git`
2.  Edit `PKGBUILD` so that `BRANCH=emacs26-git`

```
==> Starting pkgver()...
==> Updated version: emacs26-git 26.1.50.132021-1
==> Sources are ready.
Could not find PKGDEST for: emacs-git
```

**Comment by Morganamilo** [comment] 2018-07-26 19:09
Sounds like a makepkg problem. Try to reproduce it with makepkg.

**Comment by Morganamilo** [comment] 2018-07-26 19:39
Actually wait, that is an error. What's the output of `makepkg --packagelist`?

**Comment by zhou13** [comment] 2018-07-26 20:20
`cd ~/.cache/yay/emacs-git && makepkg -si` works for me.

`makepkg --packagelist` returns
````
/home/zyc/.cache/yay/emacs-git/emacs26-git-26.1.50.132021-1-x86_64.pkg.tar.xz
````

**Comment by Morganamilo** [comment] 2018-07-26 21:11
I have time to test myself now. The clone is taking a while though....

Anyway this package has weird all over. Changing the branch to emacs26 also changes the pkgname. I think that might be part of the problem. There's also a separate emacs26 package on the AUR but it conflicts with emacs and also depends on emacs-git so it's uninstallable.

the --packagelist looks normal apart from the pkgname change. I'll see if it's reproducible on my side.

**Comment by Morganamilo** [comment] 2018-07-26 21:20
Yep, yay is looking for the PKDEST of emacs-git but the package has been renamed to emacs26-git so it can't find it.

I think this is a wontfix. We rely on the RPC and we don't expect the pkgname to suddenly change on us. As far as the AUR package goes I'm not too sure if packages like should exist. A better idea might be to just upload a separate emacs-26 package.

For a quick fix you could also edit the pkgbuild to it keeps the pkgname. Then you'll still have emacs26 it will just be called emacs-git.

**Comment by Morganamilo** [comment] 2018-07-26 21:46
Although thinking about it. You do have to edit the pkgbuild for it to pull that pkgname swap so I guess it can be forgiven there. So I wont bother with a deletion request as the pkgbuild seems decent as long as you don't edit it. emacs26-git however has now been deleted.

**Comment by palopezv** [comment] 2018-07-26 23:35
As the author of the emacs-git package, I have this statement to make: 

**AUR helpers are not supported.**

The reason should be obvious. It is a complex script and the end user is expected to know what he/she is doing. Running development versions of software is not something you expect of someone who can't fix problems along the way.

**Comment by Morganamilo** [comment] 2018-07-26 23:42
I already put this off as a wontfix instead of declaring it as a problem with your pkgbuild.

Although you might want to consider putting up a separate emacs26-git package. I don't like the idea of a pkgbuild being able to change it's pkgname. But as I noted above it's not that big of a deal.

**Comment by palopezv** [comment] 2018-07-26 23:54
I had a dummy package with a hard dependency on emacs-git but some bright soul asked for its deletion some 10 hours ago (from the time on this post) and it was acted upon with astonishing alacrity. I won't be restoring that package because it would be a pointless exercise of what-a-mole. I'll see how I can add it as a split package.

On the other hand, as it is a VCS package, I don't really see the point of using an AUR helper to install it, much less manage it. The local repo is big, and getting bigger everyday, and you should read the repo log before you decide to update in case something is in transition or broken at that moment in time. Makepkg is a better option in such use case, TBH.

**Comment by Morganamilo** [comment] 2018-07-27 00:07
The AUR is for packages. There are some dummy packages on the AUR but they at least serve the purpose of satisfying dependencies.

Your 'package' was just some message and due to the dependency on emacs-git, you wouldn't even see the message until you installed emacs-git. On top of that there was an `exit 1` in there and a conflict on emacs which makes it unbuildable and uninstallable.

So all that considered I wouldn't even call it a package. You say you don't support AUR helpers and I agree no one should. They are unsupported by the AUR. And you expect people to know what they're doing, weird that you would create such a handholdy 'package'.

Anyway that's why I deleted it.

**Comment by palopezv** [comment] 2018-07-27 00:39
Fair enough. Just so you know my rationale, I've dealt over the few years I've maintained some packages AUR with people who shouldn't even be allowed to own a rotary phone. As you are evidently the bright soul, may I point out that you are trying to have your cake and eat it too?

**Comment by Morganamilo** [comment] 2018-07-27 00:45
>may I point out that you are trying to have your cake and eat it too?

How so exactly?

**Closed** 2018-07-27 12:56 UTC
Labels: wontfix
