### ISSUE TITLE
Fix up PKGBUILD with new release

### ISSUE THREAD

**Issue by Morganamilo** [Jguer/yay#581] opened 2018-07-23 23:21 UTC
PKGBUILDs do not need to list reverse conflicts, they will be figured out by pacman.

`yay` does not need to conflict with anything
`yay-bin` and `yay-git` should only conflict with`yay`. They both provide `yay` so each package will still conflict with each other.

yay's conflict resolving is good enough and should detect this.

Low priority though, probably not worth doing it now. Just do it next time we update the pkgbuilds.

**Comment by Jguer** [comment] 2018-07-25 11:54
I will do it on the new release, no problem

**Comment by Morganamilo** [comment] 2018-07-30 15:18
By the way, libalpm is MIT and seems as it's built into Yay shouldn't the `licences=()` include that? Or you could just change libalpm to GPL3. Also I believe the you should use GPL3 instead of GPL as it implies 2 or later while all of our stuff depends explicitly on 3 or later.

**Comment by Jguer** [comment] 2018-07-31 09:02
Does MIT allow you to re-license your fork even if you're not the original license holder?
```
A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.
```
I think we qualify for redistribution under different terms

**Comment by rmarquis** [comment] 2018-07-31 12:43
Yes, MIT-licensed work can be integrated or made into GPL-licensed software. However, yay doesn't distribute the libalpm code itself, but rather it links to it at build time. You thus don't need to relicense the libalpm code.

Alternatively and in case of doubt, you could also relicense yay code to MIT. You'd need approval of past contributor though.

**Comment by Morganamilo** [comment] 2018-07-31 13:26
It's a static link though. Which makes the go-alpm code part of the yay package. That's why I was thinking the pkgbuild should have MIT in its licences just as a heads up "this package contains GPL and MIT code". Is that not the case?

> (on an unrelated note, I'm amazed how you guys slip to unrelated topic in issues so easily).

Eh this issue can be seen as "fix up pkgbuild". Reverse conflicts is just the first point I thought off.

**Comment by Morganamilo** [comment] 2018-07-31 13:31
And now we're on topic again ;)

**Comment by rmarquis** [comment] 2018-07-31 14:18
> It's a static link though. Which makes the go-alpm code part of the yay package.

I mean the libalpm _source_. You don't need to relicense source code you don't distribute. And since MIT is compatible with the GPL, there is no issue with static linking (the reverse is not true though). I guess you could say the "resulting binary is GPL-licensed", if that makes any sense.

**Comment by Morganamilo** [comment] 2018-07-31 14:26
I think I might have confused you here. I was talking about go-alpm, out bindings for libalpm. Although I realise I mistakenly said libalpm above. Sorry for the confusion.

**Comment by rmarquis** [comment] 2018-07-31 14:31
Yes, but the issue is the very same: go-alpm is under MIT, and statically linked. You don't need to re-license go-alpm since the MIT is compatible with the GPL.

This whole discussion is a clear example why MIT-like licensing is preferred to the GPL: it's clear and concise, and actually readable without being a lawyer by anybody :P

**Comment by Morganamilo** [comment] 2018-07-31 14:39
Well the question I was asking is. Because go-alpm is MIT and statically linked, should the yay package include MIT in its licence array? And also half heartily mentioned re licencing it.

**Comment by rmarquis** [comment] 2018-07-31 14:42
The short answer is 'no'.

Also, I'd say re-licensing go-alpm to the GPL is more a disservice to any project that want to use it but dislike the GPL for some reason (as the compatibility is one way only).

**Comment by Morganamilo** [comment] 2018-07-31 14:52
>The short answer is 'no'.

Alright I'll take your word on it, thanks.

>Also, I'd say re-licensing go-alpm to the GPL is more a disservice to any project that want to use it but dislike the GPL for some reason (as the compatibility is one way only).

Personally I prefer GPL to MIT. Forcing anybody using my code to keep it open is something I want (Not that I really expect anybody to use my code). But yeah, go-alpm was not started by me or jguer so I would feel bad about re licensing some one else's project. I was just listing the possibilities.

**Comment by Jguer** [comment] 2018-07-31 15:42
`yay` is such a specific application anyway, GPL made sense for it. `go-alpm` was MIT licensed which I saw as a plus when browsing around what had been written connecting go and arch. I say it stays as it is and the go runtime is BSD so then we should include the BSD license as well following the same logic
```
licenses github.com/jguer/yay
github.com/jguer/yay                                           GNU General Public License v3.0
github.com/jguer/yay/vendor/github.com/Morganamilo/go-srcinfo  GNU General Public License v3.0
github.com/jguer/yay/vendor/github.com/jguer/go-alpm           MIT License (98%)
github.com/jguer/yay/vendor/github.com/mikkeloscar/aur         GNU General Public License v3.0
```

**Comment by rmarquis** [comment] 2018-07-31 16:00
Also, another possibility that hasn't be mentioned is [multi-licensing](https://en.wikipedia.org/wiki/Multi-licensing), so you could licence go-alpm under both the MIT and GPL.

**Comment by AladW** [comment] 2018-08-01 20:33
>(on an unrelated note, I'm amazed how you guys slip to unrelated topic in issues so easily).

Call it a healthy work-environment.

**Comment by Morganamilo** [comment] 2018-08-01 20:39
For more off topic. Nice work you and Svito did on the wiki recently. (I feel bad for suggesting stuff in the talk then you guys doing all the work)

**Comment by AladW** [comment] 2018-08-01 21:00
Don't worry, we get plenty satisfaction from our work when @eli-schwartz deletes half the helpers from the AUR as a result. :wink:

**Comment by eli-schwartz** [comment] 2018-08-01 21:13
yay contains both MIT and GPL code, I see no reason why that should be different from any other such package.

If yay depended on a system version of go-alpm, then it would be only GPL, and you would then check and see that it depends on and links to an MIT library.

Either way, the combined work is ultimately GPL, since GPL imposes additional restrictions on top of MIT but does not violate any of the terms of MIT.

...

Relicensing go-alpm seems kind of silly, since you can only relicense your fork but anyone who wants to use the original license can simply get the source from the original location. Relicensing as dual GPL/MIT makes even less sense, because if you're okay with MIT then offering a GPL license does nothing and gives no additional benefits AFAIK.

**Comment by Morganamilo** [comment] 2018-08-01 21:40
Thanks for the clarification. I will reiterate though. Re-licencing was just something I mentioned as something we technically could do. I do agree that it's silly and I have no plans to do that.

P.S. if you wanna continue your deletion crusade, seems as you deleted yaourt-gui, maybe this applies too?  https://aur.archlinux.org/packages/pakku-gui/

**Comment by eli-schwartz** [comment] 2018-08-01 21:53
I read the yaourt-gui source code and decided it was too dangerous to remain. :p

Feel free to submit deletion requests for any other packages you think should not be on the AUR, along with your justification... but keep in mind also, that just because it is a gui does not mean it should not be allowed. I mean, I think I'd like to delete octopi too, but I lack sufficient justification since AFAIK if you only use it and don't use other libalpm frontends, it doesn't actually do partial updates... it's not completely incompetent trash (just partially incompetent / generally questionable of-dubious-value that can easily mess you up given certain conditions the developer claims not to expect).

**Comment by Morganamilo** [comment] 2018-08-01 22:02
>Feel free to submit deletion requests for any other packages you think should not be on the AUR

I do and have submitted many already :)

>that just because it is a gui does not mean it should not be allowed

I'm aware of that, that's why I was leaving it to your discretion. Although my reasons was because it basically pops pakku open in a new terminal and that's all, not because of security.

**Comment by AladW** [comment] 2018-08-01 23:11
>I read the yaourt-gui source code and decided it was too dangerous to remain. :p

I think you missed one: https://aur.archlinux.org/packages/yaourt-gui/ (there was a second which was "yaourt-gui-manjaro", whatever that means)

**Comment by eli-schwartz** [comment] 2018-08-01 23:18
Oof.

**Comment by Jguer** [comment] 2018-08-06 21:34
Yes, I messed it up with the automated scripts, it will be fixed next release

**Closed** 2018-08-31 21:01 UTC
Labels: enhancement
