### ISSUE TITLE
yay creates "$HOME" directory within the user's home directory.

### ISSUE THREAD

**Issue by meganukebmp** [Jguer/yay#686] opened 2018-09-04 21:45 UTC
#### Affected Version

yay v8.1110
#### Issue
Yay seems to create a new directory called `$HOME` within the user's actual home directory. Likely not respecting the $HOME environment variable or code error. Seems to only do this for the .config directory however.
#### Steps to reproduce

1. Run any yay command such as `yay -Syy`
2. Check user's home directory

**Comment by parkerlreed** [comment] 2018-09-04 21:56
Cannot reproduce here

````
[parker@e55 ~]$ yay -Syu
...
...
[parker@e55 ~]$ yay --version
yay v8.1110.r0.ga109ea4 - libalpm v11.0.1
[parker@e55 ~]$ ls
 build     Documents   Games   Mu      Native2Proton   Public                      Templates  'VirtualBox VMs'
 Desktop   Downloads   go      Music   Pictures       'SEGA Mega Drive Classics'   Videos
````

**Comment by Morganamilo** [comment] 2018-09-04 21:58
@parkerlreed you might not be able to reproduce it because you have an older config that has the full path. Either way it definitely occurs, just that the file is created in the current directory, not the home directory.

I'll fix it then I'm leaving the file handling to @Jguer and never going near it again.

**Comment by Morganamilo** [comment] 2018-09-04 22:08
Should be fixed in git now.

**Comment by Morganamilo** [comment] 2018-09-04 22:10
Also for removing that directory. I would probably opt for `rm -ri '$HOME'`.

**Comment by Morganamilo** [comment] 2018-09-04 22:26
Also I believe people will only be effected by this bug if they started using yay (or reset the config) in the past 4 days. So not as catastrophic as it seems. As I said this is probably why @parkerlreed isn't effected.

@meganukebmp Is this the case for you?

**Closed** 2018-09-04 22:32 UTC

**Comment by meganukebmp** [comment] 2018-09-04 23:58
@Morganamiloa switched to yay just a few hours ago so yeah. Thanks for reacting so fast and resolving the issue!

**Comment by Jguer** [comment] 2018-09-05 08:18
Pushing a new release

> I'll fix it then I'm leaving the file handling to @Jguer and never going near it again.

:rofl:
