### ISSUE TITLE
Garbled output when downloading sources - Display of multiple downloads from AUR overlap

### ISSUE THREAD

**Issue by mbwgh** [Jguer/yay#1620] opened 2021-10-24 15:42 UTC
### Affected Version

`yay v11.0.1 - libalpm v13.0.1` (before the upgrade)
`yay v11.0.2 - libalpm v13.0.1` (after)

### Describe the bug

When downloading sources for a full system upgrade, output is garbled, but only during the download phase. 
![2021-10-24-172706_1920x838_scrot](https://user-images.githubusercontent.com/28275377/138601413-58d95d10-cf53-4049-b796-746619bc57e6.png)

### Reproduction Steps

1. `$ yay`
2. Do a full system upgrade where several sources have to be fetched

### Expected behavior

Output for concurrent (if that is it?) downloads should not become mangled and appear as one line per download.

### Output

`yay -Pg`:

```sh
{
	"aururl": "https://aur.archlinux.org",
	"buildDir": "/home/mbw/.cache/yay",
	"editor": "",
	"editorflags": "",
	"makepkgbin": "makepkg",
	"makepkgconf": "",
	"pacmanbin": "pacman",
	"pacmanconf": "/etc/pacman.conf",
	"redownload": "no",
	"rebuild": "no",
	"answerclean": "",
	"answerdiff": "",
	"answeredit": "",
	"answerupgrade": "",
	"gitbin": "git",
	"gpgbin": "gpg",
	"gpgflags": "",
	"mflags": "",
	"sortby": "votes",
	"searchby": "name-desc",
	"gitflags": "",
	"removemake": "ask",
	"sudobin": "sudo",
	"sudoflags": "",
	"requestsplitn": 150,
	"sortmode": 0,
	"completionrefreshtime": 7,
	"sudoloop": false,
	"timeupdate": false,
	"devel": false,
	"cleanAfter": false,
	"provides": true,
	"pgpfetch": true,
	"upgrademenu": true,
	"cleanmenu": true,
	"diffmenu": true,
	"editmenu": false,
	"combinedupgrade": false,
	"useask": false,
	"batchinstall": false
}
```

**Comment by Jguer** [comment] 2021-10-25 18:17
This bug (more unimplemented feature) is confirmed. Currently concurrent download just throws all the output to stdout.

Ideas welcome

**Comment by mbwgh** [comment] 2021-10-26 06:40
> This bug (more unimplemented feature) is confirmed. Currently concurrent download just throws all the output to stdout.
> 
> Ideas welcome

I don't speak `go`, but on a high level I'd maybe try to approach the problem like the following.

There is a maximum of `N <= 25` concurrent download threads, often, much less. It should thus be realistic to stack `N` progress indicators on top of each other and update them inplace (assuming the shell supports this), similar to how docker does this.

In `PKGBUILDRepos` instead of using a single `progress` int, I'd try using an an array of progress values or probably directly the string to output, one for each running job. You'd need to keep track of the job number, or maybe it  can be queried from the semaphore.
These progress array elements would not need to be synchronized then.

Output would be done only in the main thread (then I don't think you'd even need the mutex?). You can set the shell's vertical cursor position with dedicated escape characters or by shelling out to something like `tput`, but it may be tricky to make this play nicely with every shell or terminal emulator out there.

**Comment by myknbani** [comment] 2022-01-02 06:50
It seems more like a regression.  I don't remember this garbling bug as a longtime `yay` user. 

EDIT:  I also turned on `ParallelDownloads = 5` in `/etc/pacman.conf` recently, so I'm not sure if that affects things.

**Comment by chandujr** [comment] 2022-12-10 14:53
> I also turned on `ParallelDownloads = 5` in `/etc/pacman.conf` recently, so I'm not sure if that affects things.

I don't have parallel downloads enabled, but still getting this jumbled log.

**Comment by afiorillo** [comment] 2022-12-15 16:05
I found some time to dig into this a bit and can hopefully at least share some insights.

As far as I can tell, this originates in yay when it's actually executing all of the makepkg commands. In `downloadPKGBUILDSourceFanout` ([link](https://github.com/Jguer/yay/blob/next/aur_source.go#L66)) it sends off one goroutine per PKGBUILD and allows up to N concurrent workers (defaulting to number of CPU cores). Each of these eventually constructs a makepkg command ([link](https://github.com/Jguer/yay/blob/next/pkg/settings/exe/cmd_builder.go#L78)) and then runs [Show](https://github.com/Jguer/yay/blob/next/pkg/settings/exe/exec.go#L18) which just spews stdout/stderr to the terminal. By this point it's just `yay` running N concurrent `makepkg` commands (with the PKGBUILDs downloaded but not the sources).

The console messages such as "Retrieving packages..." and "downloading..." actually come from makepkg -- [here](https://gitlab.archlinux.org/pacman/pacman/-/blob/0fe764a253607a2b3fef202289c5bc42c85a75ba/src/pacman/callback.c) namely. According to the Git blame, some changes were made to the cursor positioning in the progress bar about 2 years ago, which would line up with when I think this issue started happening to yay. 

I think the easiest option would be to just disable the progress bar. This can be done with the `--noprogressbar` flag when calling makepkg or by uncommenting the `#NoProgressBar` line in `/etc/pacman.conf`. This is just a workaround though and would write that it's downloading the file, though no status information. That said, given how messy it is, I doubt anyone is getting status information currently. The flag could be added to the command builder in yay so as to not affect users' plain pacman usage.

To keep status information I don't see many options. One could be to have `yay` capture stdout/stderr from the individual makepkg processes, somehow keep those pipes isolated and selectively write the output in a nicer format.

It seems like Pacman does internally support concurrent downloads (hence the `ParallelDownloads` configuration mentioned above) but the way `yay` is using it doesn't touch this. `yay` creates N independent `pacman` processes, rather than 1 process with N packages. If the install workflow instead bundled all of the makepkg commands into one (somehow, though I'm unsure if makepkg allows this) then that could be an alternative solution.

Edit: of course that isn't the end of the story. Elsewhere in makepkg, sometimes it calls curl instead of uses the custom progress bar inside of Pacman. In particular, [download_file](https://gitlab.archlinux.org/pacman/pacman/-/blob/0e938f188692c710be36f9dd9ea7b94381aed1b4/scripts/libmakepkg/source/file.sh.in) pulls the appropriate "[download agent](https://gitlab.archlinux.org/pacman/pacman/-/blob/e1ce2351f5c00dd90104e0f4ce3bf176da28af08/etc/makepkg.conf.in)," which seems to be different ways of calling curl. When I tested with `yay anki`, the dependencies of anki were all downloaded with Pacman (and because I modified the pacman conf the progress bars were suppressed), but anki itself was downloaded with that shell script and still spat out curl's progress bar. Interestingly, curl also [supports parallel transfers](https://github.com/curl/curl/blob/master/docs/PARALLEL-TRANSFERS.md), but I would say it's nearly hopeless to use that here -- yay is making N makepkg processes, each of which makes an independent curl process; to consolidate it into one curl process would be an enormous undertaking.

**Comment by Jguer** [comment] 2022-12-15 20:21
Nice research @afiorillo, the garbled output is indeed a consequence of the parallel sourcing of packages and not treating its output correctly. Maybe there is a better way of aggregating the output (the no progress is a nice idea).

`maxconcurrentdownloads` can be used to limit to one download a time and have a proper display. 

It's my opinion now that the concurrent downloads are not that useful (specially in it's current form) and it would be better to remove the feature/option but it hasn't been costly to maintain

**Comment by Ali-Aref** [comment] 2023-07-02 01:27
Same here, any solutions ?

**Comment by miyaokamarina** [comment] 2023-07-04 17:09
Well, it can be worked around like this:

1. Call `makepkg` with a custom `--config` with `DLAGENTS` substituted by wrappers, that report progress in a machine-readable way.
2. Then interpret the reported progress internally, multiplex it like `pacman` does, and print the combined result to the console.

The custom config should just source the original one, and then override the `DLAGENTS` variable. Well, it _can_ break thing and introduce new issues in certain edge cases[^1], but I think it's worth it.

[^1]: For example, if the user relies on a custom agent, specified in the existing `makepkg.conf`. Well, it can be in turn worked around by another config option, that prevents `DLAGENTS` overriding or not overriding the variable at all, if it already exists.

**Comment by Naik-Bharat** [comment] 2023-09-15 14:21
I believe the current output during source downloads is not very useful due to its garbled nature. It would be more sensible to download the sources sequentially rather than concurrently. 

Let me know if it sounds good as I'd like to contribute to resolving this issue.

**Closed as completed** 2023-09-18 07:51 UTC
Labels: Type: Enhancement, Status: Confirmed
