### ISSUE TITLE
AUR: Skip failed package during bulk upgrade

### ISSUE THREAD

**Issue by Avinash-Bhat** [Jguer/yay#1548] opened 2021-07-10 16:25 UTC
### Problem
When upgrading the AUR packages (yay -Syu --aur), the whole operation fails when some configuration error is there with upgrading a single package.

for example, during a recent upgrade, the git repo for brave-bin caused failure like below:
```
...
error merging brave-bin: error: Could not read 215f580b5eae2a9b1e6bfbdcb489720e8e96fe0b
error: Could not read 215f580b5eae2a9b1e6bfbdcb489720e8e96fe0b
error: Could not read 215f580b5eae2a9b1e6bfbdcb489720e8e96fe0b
fatal: refusing to merge unrelated histories
```
The cause for this was due to some changes done for diverging, which shouldn't affect the AUR upgrade, and treat it as an ignored package.

### The solution
adding an arg `--proceed-on-fail` or like thereof to consider failure of a package as a criteria for ignoring it 

### Alternatives considered
Currently there are no alternative other than ignore the failing packages manually

**Comment by mrskug** [comment] 2021-07-27 16:13
See #1126

**Comment by Jguer** [comment] 2021-08-31 00:32
Closing as duplicate of https://github.com/Jguer/yay/issues/848

**Closed as completed by Jguer** 2021-08-31 00:32 UTC
Labels: Type: Feature Request, Status: Discussion Open
