### ISSUE TITLE
yay -c doesn't work

### ISSUE THREAD

**Issue by sanngridhr** [Jguer/yay#2099] opened 2023-04-09 11:02 UTC
### Affected Version

yay v12.0.3 - libalpm v13.0.2

### Describe the bug

`yay -c` straight up doesn't work

### Expected behavior

Cleaning up unneeded packages

### Output

```fish
❯ yay -c --debug
[DEBUG:runner] running /usr/bin/sudo -v
[DEBUG:runner] running /usr/bin/sudo -B pacman --debug -S -c -y -u --config /etc/pacman.conf --
[DEBUG:runner] running /usr/bin/sudo -v
помилка: недійсний параметр: "--clean" і "--refresh" не можна використовувати разом
 -> exit status 1
```

**Comment by FriendsNone** [comment] 2023-04-10 07:18
Can confirm on my side, with the same version. `-c` and `--clean` does not work.

**Comment by petrzjunior** [comment] 2023-04-10 10:20
Duplicate of https://github.com/Jguer/yay/issues/2049

**Comment by sanngridhr** [comment] 2023-04-10 12:47
Thanks

**Closed as completed** 2023-04-10 12:47 UTC
Labels: Type: Bug, Status: Triage
