### ISSUE TITLE
Error after update pacman 

### ISSUE THREAD

**Issue by erickwill** [Jguer/yay#2395] opened 2024-03-13 14:46 UTC
After regular update of pacman, yay stopped to work:

```
yay -Sc
yay: error while loading shared libraries: libalpm.so.13: cannot open shared object file: No such file or directory
```

I'm using Arch Linux, rolling release.

**Comment by Trit34** [comment] 2024-03-13 14:56
Duplicate of https://github.com/Jguer/yay/issues/2393

**Closed as completed** 2024-03-13 16:02 UTC
Labels: Type: Bug, Status: Triage, Status: Duplicate
