### ISSUE TITLE
AURSHOWDIFF=1

### ISSUE THREAD

**Issue by vinipsmaker** [Jguer/yay#344] opened 2018-04-09 19:11 UTC
The same as `yaourt`: https://github.com/archlinuxfr/yaourt/blob/fe1bcdd8610230bb75289f4b4c43607346ad18a9/src/man/yaourtrc.5#L164

I think it depends on this first: https://github.com/Jguer/yay/pull/297

**Comment by Morganamilo** [comment] 2018-04-09 20:15
It's possible to do diffs while still using the tarball method. I'm still undecided whether it's worth the effort though. We tend to prefer flags and config values over environment variables so this will most likely be implemented as `--showdiffs` or something.

This is a duplicate of #131 so I'm closing this in favour of that issue.

**Closed by Morganamilo** 2018-04-09 20:15 UTC
